### ISSUE TITLE
Cuckoo Web TemplateSyntaxError when checking behavioral analysis 

### ISSUE THREAD

**Issue by simuset** [cuckoosandbox/cuckoo#2054] opened 2018-01-10 14:58 UTC
Hi,
I'm having problems with cuckoo web when attempting to check the behavioral analysis results. 
Whenever I try to click on the link the following error is displayed:

![image](https://user-images.githubusercontent.com/35301938/34778933-0c98de46-f61f-11e7-8dc1-cb436c17f17d.png)

**Comment by doomedraven** [comment] 2018-01-10 18:11
are you dure what you using this cuckoo? the django which you use isn't used in this version, update to latest version

**Comment by simuset** [comment] 2018-01-10 18:37
I am using Cuckoo version 2.0.5 and the setup.py file says that it requires django version 1.8.4, which is the one I have installed. Which django version are you referring to ?

**Comment by doomedraven** [comment] 2018-01-10 18:38
nvm i have crossed versions of cuckoos :D

**Comment by jbremer** [comment] 2018-02-04 09:44
I believe I know why this is happening, but I can't seem to reproduce it. Do you have any special configuration options going on? Or could you share the analysis?

**Comment by nkleck** [comment] 2018-02-09 15:35
I too have been getting this issue. all the other pages load except the behavior page. I dont have any custom configurations. Its a cuckoo installation to /opt/cuckoo and made cuckoo cwd /opt/cuckoo
i run cuckoo with supervisord
enabled the rest api


processing.conf
[behavior]
enabled = yes

here is the package list
`$ pip list
alembic (0.8.8)
androguard (3.0.1)
asn1crypto (0.23.0)
beautifulsoup4 (4.5.3)
cairocffi (0.8.0)
CairoSVG (1.0.22)
capstone (3.0.5rc2)
certifi (2017.11.5)
cffi (1.11.2)
chardet (2.3.0)
click (6.6)
colorama (0.3.7)
cryptography (2.1.3)
cssselect (1.0.1)
Cuckoo (2.0.4.4)
distorm3 (3.3.4)
Django (1.8.4)
django-extensions (1.6.7)
dpkt (1.8.7)
ecdsa (0.13)
egghatch (0.2.1)
elasticsearch (5.3.0)
enum34 (1.1.6)
et-xmlfile (1.0.1)
Flask (0.12.2)
Flask-SQLAlchemy (2.1)
functools32 (3.2.3.post2)
html5lib (0.999999999)
HTTPReplay (0.2.1)
idna (2.6)
ipaddress (1.0.18)
itsdangerous (0.24)
jdcal (1.3)
Jinja2 (2.9.6)
jsbeautifier (1.6.2)
jsonschema (2.6.0)
libvirt-python (3.9.0)
lxml (4.1.1)
M2Crypto (0.24.0)
Mako (1.0.7)
MarkupSafe (1.0)
meld3 (1.0.2)
olefile (0.43)
oletools (0.42)
openpyxl (2.4.9)
peepdf (0.3.6)
pefile2 (1.2.11)
Pillow (3.2.0)
pip (9.0.1)
psycopg2 (2.7.3.2)
pycparser (2.18)
pycrypto (2.6.1)
pydeep (0.2)
pyelftools (0.24)
pymisp (2.4.54)
pymongo (3.0.3)
pyOpenSSL (17.3.0)
Pyphen (0.9.4)
Pyste (0.9.10)
python-dateutil (2.4.2)
python-editor (1.0.3)
python-magic (0.4.12)
pythonaes (1.0)
pytz (2017.3)
PyV8 (1.0.dev0)
pyvmomi (6.5.0.2017.5.post1)
requests (2.13.0)
scapy (2.3.2)
setuptools (36.7.2)
SFlock (0.2.17)
six (1.11.0)
SQLAlchemy (1.0.8)
supervisor (3.2.0)
suricatasc (0.9)
tinycss (0.4)
tlslite-ng (0.6.0)
ujson (1.35)
unicorn (1.0.1)
urllib3 (1.22)
virtualenv (15.0.1)
volatility (2.6)
wakeonlan (0.2.2)
WeasyPrint (0.36)
webencodings (0.5.1)
Werkzeug (0.12.2)
wheel (0.29.0)
yara-python (3.6.3)`

below is traceback from the web when getting the above template error
`Internal Server Error: /analysis/28/behavior/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/routes.py", line 43, in detail
    report=report, page=page
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/utils.py", line 83, in render_template
    request, template_name, kwargs, status=kwargs.pop("status", 200)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 655, in resolve
    return string_if_invalid % self.var
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/settings.py", line 204, in __mod__
    "Undefined variable or unknown value for: %s" % other
TemplateSyntaxError: Undefined variable or unknown value for: process.calls
2018-02-09 09:49:34,616 [django.request] ERROR: Internal Server Error: /analysis/28/behavior/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/routes.py", line 43, in detail
    report=report, page=page
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/utils.py", line 83, in render_template
    request, template_name, kwargs, status=kwargs.pop("status", 200)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 655, in resolve
    return string_if_invalid % self.var
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/settings.py", line 204, in __mod__
    "Undefined variable or unknown value for: %s" % other
TemplateSyntaxError: Undefined variable or unknown value for: process.calls
[09/Feb/2018 09:50:30] "GET /analysis/28/behavior/ HTTP/1.1" 500 438705
- Broken pipe from ('10.10.10.53', 56450)
[09/Feb/2018 09:51:02] "GET /analysis/28/behavior/ HTTP/1.1" 500 438684`

**Comment by smolanet** [comment] 2018-03-08 19:51
Hi guys!
I had the same problem but it seems to be fixed when you change Debug parameter to False on .cuckoo/web/local_settings.py
I changed it previously due to an issue that I had in the past and I forgot to change it back after that.
Thanks!

**Comment by jbremer** [comment] 2018-03-08 19:53
This was fixed in d500624c45fe0c6b0ba9ab4b75467ecf8142815d and will be pushed as part of the upcoming release ;-)

**Comment by smolanet** [comment] 2018-03-08 20:17
Good news :) In the current release, I think only appears when you have enabled Debug parameter but nice to know it will be fixed in the upcoming one.
Thanks for your excellent work on this project, guys! @jbremer @doomedraven

**Comment by jbremer** [comment] 2018-06-12 07:04
The fix for this is part of our `2.0.6` release, closing as resolved. Thanks!

**Closed by jbremer** 2018-06-12 07:04 UTC
