### ISSUE TITLE
api.py fills /tmp

### ISSUE THREAD

**Issue by jimmythegreat** [cuckoosandbox/cuckoo#858] opened 2016-04-13 22:24 UTC
When submitting samples via api.py they upload to /tmp/cuckoo-tmp. When you delete a task it only deletes the sample in cuckoo/storage. After running Cuckoo for weeks my /tmp directory filled up.

The simple solution is to delete old files from /tmp/cuckoo-tmp via cron (old because new ones may still be in use).

Is there a better solution?

**Comment by jbremer** [comment] 2016-04-13 22:29
I created a todo item for this, #577. But as you can see not much has happened since then.
Having said that there's currently no better solution..

**Comment by jbremer** [comment] 2016-06-27 11:05
Closing this as duplicate of #577.

**Closed by jbremer** 2016-06-27 11:05 UTC
