### ISSUE TITLE
Agent doesn't works on the vm

### ISSUE THREAD

**Issue by montopinturas** [cuckoosandbox/cuckoo#1079] opened 2016-09-08 10:14 UTC
Hi,

When I execute cuckoo, my vm open the snapshot correctly but the agent doesn't Works.
I've checked the config, but I could not see anything strange.

Thanks in advance

**Comment by doomedraven** [comment] 2016-09-08 10:22
Try curl vm_ip:8000 when vm strted, if you getting error 50x mean agent works, if nop, then you have not executed correctly agent before snapshot

**Comment by montopinturas** [comment] 2016-09-08 13:48
I tried it, I don't recive any error, how I should launch the agent before make the snapshot??

Thanks

**Comment by KillerInstinct** [comment] 2016-09-08 15:12
Yes, per the documentation teh agent should be running when you are taking the screenshot.

**Comment by montopinturas** [comment] 2016-09-08 16:01
Hi KilleInstinct,

I did before make the snapshot, when I execute the analysis the snapshot open the agent but doesn't analyze.

Thanks

**Comment by doomedraven** [comment] 2016-09-08 16:09
If curl no return error your agent not working so it wont analyze nothing, you meed investigate what is wrong with your snapshot

**Comment by jbremer** [comment] 2017-02-25 11:10
Closing this issue as a duplicate of many others. @montopinturas Did you happen to resolve your issues already? If so, what steps did you undertake etc?

**Closed by jbremer** 2017-02-25 11:10 UTC
