### ISSUE TITLE
new issue "VBoxManage returns error checking status for machine windows7-cuckoo: VBoxManage: error: Could not find a registered machine named 'windows7-cuckoo'"

### ISSUE THREAD

**Issue by surajsecpro** [cuckoosandbox/cuckoo#1272] opened 2017-02-02 15:54 UTC
>i reinstalled my vbox, cuckoo and now i m getting this error everytime
>i m running 
sudo ./cuckoo.py 

>i get

VBoxManage returns error checking status for machine windows7-cuckoo: VBoxManage: error: Could not find a registered machine named 'windows7-cuckoo'

>when i try to start VM from cli  as below, i m able to start it.so whats the deal is with error.

vboxmanage startvm windows7-cuckWaiting for VM "windows7-cuckoo" to power on...
VM "windows7-cuckoo" has been successfully started.

**Comment by doomedraven** [comment] 2017-02-02 16:13
stupid question but just in case, can you see the vm on vbox gui?
or try `registervm` command

**Comment by surajsecpro** [comment] 2017-02-02 17:08
>i tried and getting following

<surajsecpro@surajsecpro-Vostro-3558:~/VirtualBox VMs$ vboxmanage registervm windows7-cuckoo
<VBoxManage: error: Runtime error opening '/home/surajsecpro/.config/VirtualBox/windows7-cuckoo' <for reading: -102(File not found.).
<VBoxManage: error: /home/vbox/vbox-5.0.32/src/VBox/Main/src-server/MachineImpl.cpp[480] <(nsresult Machine::initFromSettings(VirtualBox*, const com::Utf8Str&, const com::Guid*))
<VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, <interface IMachine, callee nsISupports
<VBoxManage: error: Context: "OpenMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line <85 of file VBoxManageMisc.cpp
>i cannot locate directory " '/home/surajsecpro/.config/VirtualBox" on my machine somehow. i have reinstalled vbox couple of times already

**Comment by doomedraven** [comment] 2017-02-02 17:33
So that is not cuckoo error, you need to find where that file is placed and re register it, and should be done

**Comment by surajsecpro** [comment] 2017-02-03 05:27
is it likely that Virtualbox is not getting installed properly on my machine

**Comment by surajsecpro** [comment] 2017-02-04 20:00
> hey doomedraven, looks like i m in a loop state :) 
i opened a question at virtualbox guys and they say its cuckoo after a long exchange of question and answers with them. you may wanna look at this 

https://forums.virtualbox.org/viewtopic.php?f=7&t=81705&p=384796#p384796

**Comment by doomedraven** [comment] 2017-02-04 20:38
But registervm still dont work? I would suggedt remove vm from vbox and read it. Or just track how cuckoo start t and play with the commands

**Comment by jbremer** [comment] 2017-02-25 02:41
@surajsecpro VirtualBox VMs are tied to a user account. You can't just create VMs with your own user and then call `sudo cuckoo.py` ;-)

**Comment by surajsecpro** [comment] 2017-02-26 06:11
oh jbremer, you gave me new insight, let me try that

**Comment by jbremer** [comment] 2017-03-05 12:23
Closing as resolved and/or not a bug directly related to Cuckoo.

**Closed by jbremer** 2017-03-05 12:23 UTC
