### ISSUE TITLE
Random office files on desktop

### ISSUE THREAD

**Issue by Neodyn** [cuckoosandbox/cuckoo#1703] opened 2017-07-11 08:16 UTC
Maybe it is an config issue or it is by design. During startup of an analyse, cuckoo seems to create random named ms office files on the desktop on my sandbox client. is ist possible to avoid this feature? I can't find anything about this issue in the documentation.

**Comment by kevthehermit** [comment] 2017-07-12 07:58
I kind of like this feature for detecting ransomware but would prefer it create them in the documents folder.

**Comment by doomedraven** [comment] 2017-07-12 10:34
" it is by design" check code, is anti-antivm trick for recent docs detection

**Comment by jbremer** [comment] 2017-07-14 16:24
Good point @kevthehermit. I'll see if I can change it to behave as such.
@Neodyn currently it's not configurable, but in the future that might make sense.

**Comment by SparkyNZL** [comment] 2017-07-16 08:00
I have to admin when i 1st saw that i freaked out, deleete all my VMs and started again, turns out the systems wasnt infected Hahahahaaaa, So funny oh so funny :)

**Comment by jbremer** [comment] 2017-09-09 11:48
The new `2.0.4` release has changed the behavior to @kevthehermit's suggestion, to the `My Documents` folder. Closing issue as resolved.

**Closed by jbremer** 2017-09-09 11:48 UTC
