### ISSUE TITLE
Cuckoo sandbox web settings problem

### ISSUE THREAD

**Issue by arunsamlegion** [cuckoosandbox/cuckoo#808] opened 2016-03-13 12:38 UTC
Error: Could not import settings 'web.settings' (Is it on sys.path?): Could not import settings 'web.settings' (Is it on sys.path?): cannot import name get_random_string. 
cuckoo/web/web/settings problem. Even if i modify wsgi.py , the error is not clearing.
 Even if i modify wsgi.py , the error is not clearing.
Also tried changing 'Web' directory but of no use. pls do help me

**Comment by doomedraven** [comment] 2016-03-13 21:57
@arunsamlegion can you tell how and from which directory you executed webgui? i just tested with last version from git and don't get any error

**Comment by arunsamlegion** [comment] 2016-03-14 09:10
I have my cuckoo at /home/cuckoo/malwaretest/cuckoo/web/ where the first 'cuckoo' is the user name of the system and second 'cuckoo' is the actual cuckoo folder.

Below is my wsgi file

import os
path='/home/cuckoo/malwaretest/cuckoo/web'
if path not in sys.path:
    sys.path.append(path)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()


![settings error](https://cloud.githubusercontent.com/assets/17810850/13739618/3d9205c6-e9f2-11e5-9205-96011ab92de0.png)
![manage error](https://cloud.githubusercontent.com/assets/17810850/13739700/ba308d46-e9f2-11e5-9bbe-0773784b145a.png)

**Comment by doomedraven** [comment] 2016-03-14 09:13
@arunsamlegion here is your error, you need execute webgui from web folder, not web/web
and to execute webgui __python manage.py runserver 0.0.0.0:8000__ replace 0.0.0.0 to your interface if need and change port if you want

**Comment by arunsamlegion** [comment] 2016-03-14 09:34
![manage2](https://cloud.githubusercontent.com/assets/17810850/13740245/b161c786-e9f5-11e5-9adf-0fc4e6ad3aba.png)
 @doomedraven I am running the manage.py from web, not from web/web. I just wanted to show you the error that occured when the settings file was executed.
I have changed the address too. Doesn't seem to work.

Can you please check if my Wsgi.py file is correct

**Comment by doomedraven** [comment] 2016-03-14 09:37
@arunsamlegion my wsgi.py

````
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "web.settings")
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

try this, if not works, can you tell django version also?

**Comment by arunsamlegion** [comment] 2016-03-14 09:44
By default my wsgi file was like that. It didn't run that time too.
My django version is 1.3

**Comment by doomedraven** [comment] 2016-03-14 09:45
my one is 1.8.4. and i don't have that problem, i would suggest update it, as it too old

**Comment by arunsamlegion** [comment] 2016-03-14 09:46
Ok, I will try that and get back to you

Thanks :)

**Comment by arunsamlegion** [comment] 2016-03-14 10:17
I updated my django. Still the same result

**Comment by doomedraven** [comment] 2016-03-14 10:29
also which version of python?

and try `sudo pip install -r requirements.txt` probably some lib missed

**Comment by arunsamlegion** [comment] 2016-03-14 13:32
@doomedraven I have python latest installed and all the lib files are uptodate

**Comment by doomedraven** [comment] 2016-03-14 20:38
@arunsamlegion 2.7.11? just in case, is strange that error, i can't reproduce it

**Comment by jbremer** [comment] 2016-06-27 11:16
By default the `wsgi.py` file sets the environment variable as follows `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "web.settings")`.
Did you already resolve this issue?

**Comment by jbremer** [comment] 2016-09-04 17:01
Going to close this issue as resolved. Most likely due to running from the wrong directory and in the near feature this won't be an issue anymore anyway. Let us know if you run into any other issues.

**Closed by jbremer** 2016-09-04 17:01 UTC
