### ISSUE TITLE
cuckoo clean issue

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1256] opened 2017-01-23 04:07 UTC
This removes a number of directories which cuckoo needs to operate

.cuckoo/storage/analysis
.cuckoo/storage/binaries
.cuckoo/logs

cuckoo error below.

=== Exception details ===
Cuckoo version: 2.0.0
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0 attrs:15.2.0 beautifulsoup4:4.4.1 blinker:1.3 bson:0.4.3 cffi:1.9.1 characteristic:14.3.0 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:1.7.1 cuckoo:2.0.0 debtags:2.0 defer:1.0.6 dirspec:13.10 distlib:0.2.2 distorm3:3.3.0 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 duplicity:0.7.6 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.1.6 flask:0.10.1 functools32:3.2.3.post2 html5lib:0.999 httplib2:0.9.1 httpreplay:0.1.17 idna:2.2 ipaddress:1.0.18 itsdangerous:0.24 jdcal:1.0 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.5.1 lockfile:0.12.2 lxml:3.6.0 m2crypto:0.24.0 mako:1.0.6 markupsafe:0.23 mysql-python:1.2.5 mysql:0.0.1 ndg-httpsclient:0.4.2 oauthlib:1.0.3 olefile:0.43 oletools:0.42 oneconf:0.3.9 openpyxl:2.3.0 pam:0.4.2 peepdf:0.3.2 pefile2:1.2.11 pefile:1.2.10.post139 pillow:3.2.0 pip:9.0.1 piston-mini-client:0.7.5 ply:3.7 psycopg2:2.6.2 py:1.4.31 pyasn1-modules:0.0.7 pyasn1:0.1.9 pycparser:2.17 pycrypto:2.6.1 pycups:1.9.73 pydeep:0.4 pygobject:3.20.0 pyjwt:1.3.0 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:16.2.0 pyserial:3.0.1 pytest:2.8.7 python-apt:1.1.0b1 python-dateutil:2.4.2 python-debian:0.1.27 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pytz:2016.10 pyxdg:0.25 requests:2.7.0 scapy:2.3.2 service-identity:16.0.0 setuptools:33.1.1 sflock:0.2.2 six:1.10.0 software-center-aptd-plugins:0.0.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0a3 twisted:16.0.0 typing:3.5.2.2 ubuntuone-client-data:14.4 unity-lens-photos:1.0 urllib3:1.19.1 vboxapi:1.0 volatility:2.5 wakeonlan:0.2.2 werkzeug:0.11.15 wheel:0.29.0 xenapi:1.2 yara-python:3.4.0 zope.interface:4.1.3

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 187, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 115, in cuckoo_init
    init_logging(level)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 126, in init_logging
    init_logger(log, "cuckoo.log")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 107, in init_logger
    l = logging.handlers.WatchedFileHandler(cwd("log", "cuckoo.log"))
  File "/usr/lib/python2.7/logging/handlers.py", line 391, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/adroot/.cuckoo/log/cuckoo.log'

creating these directories fixes the issues, but might want to incorporate this into the clean module

**Comment by jbremer** [comment] 2017-01-29 12:28
Thanks for the bug report! Interestingly enough I ran into the same issue and fixed it a few days before your report, see also fd6620002938eea7128e34ba65f2892c4ca63930. Closing this issue as resolved :-)

**Comment by doomedraven** [comment] 2017-01-29 14:01
getting approach of this issue, if you go to webgui -> admin and press remove it trigger error 500

**Comment by jbremer** [comment] 2017-01-29 14:02
Can you elaborate a little bit more on that @doomedraven?

**Comment by doomedraven** [comment] 2017-01-29 14:11
i will try to provide info later when will have a bit of time(in few hours), i tried to get quick info but for some reason now webgui not starting :D

**Comment by doomedraven** [comment] 2017-01-29 15:12
ok got it working, so, few more things
when im on the status page of analysis like `http://X/submit/post/?id=5` and i press the target, it redirects me to `http://X/submit/post/5/summary` and im getting 
```
Error 
No task ids specified
```

in webgui console i see `[29/Jan/2017 x:x:24] "GET /submit/post/5/summary HTTP/1.1" 500 14000`

* when i go to options -> delete i'm getting error 500 on webgui and in terminal

```
Traceback (most recent call last):
  File "/opt/cuckoo_package/cuckoo/lib/python2.7/site-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/cuckoo_package/cuckoo/lib/python2.7/site-packages/Django-1.8.4-py2.7.egg/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "./analysis/views.py", line 452, in remove
    if results_db.analysis.find({"shots": ObjectId(shot)}).count() == 1:
  File "build/bdist.linux-x86_64/egg/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "build/bdist.linux-x86_64/egg/bson/objectid.py", line 209, in __validate
    "not %s" % (text_type.__name__, type(oid)))
TypeError: id must be an instance of (bytes, unicode, ObjectId), not <type 'dict'>
2017-01-29 16:11:38,438 [django.request] ERROR: Internal Server Error: /analysis/remove/5/
Traceback (most recent call last):
  File "/opt/cuckoo_package/cuckoo/lib/python2.7/site-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/cuckoo_package/cuckoo/lib/python2.7/site-packages/Django-1.8.4-py2.7.egg/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "./analysis/views.py", line 452, in remove
    if results_db.analysis.find({"shots": ObjectId(shot)}).count() == 1:
  File "build/bdist.linux-x86_64/egg/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "build/bdist.linux-x86_64/egg/bson/objectid.py", line 209, in __validate
    "not %s" % (text_type.__name__, type(oid)))
TypeError: id must be an instance of (bytes, unicode, ObjectId), not <type 'dict'>
[29/Jan/2017 16:11:38] "GET /analysis/remove/5/ HTTP/1.1" 500 14001
```

**Comment by jbremer** [comment] 2017-01-29 15:13
Ah, gotcha, thanks! Will get it fixed.

**Comment by doomedraven** [comment] 2017-01-29 15:16
you are welcome and thanks to you :)

**Comment by SparkyNZL** [comment] 2017-02-01 01:28
awesome, I was getting that also :) I didn't want to open another report.

**Comment by jbremer** [comment] 2017-02-01 08:58
@SparkyNZL FWIW, feel free to open new issues for anything that produces a stacktrace ;-)

**Comment by jbremer** [comment] 2017-02-11 11:25
@doomedraven @SparkyNZL The following patch will fix the traceback above. I need some more time to properly integrate it, though.
```patch
diff --git a/cuckoo/web/analysis/views.py b/cuckoo/web/analysis/views.py
index 6a2c2a7..da0d81f 100644
--- a/cuckoo/web/analysis/views.py
+++ b/cuckoo/web/analysis/views.py
@@ -449,6 +449,21 @@ def remove(request, task_id):
 
         # Delete screenshots.
         for shot in analysis["shots"]:
+            if isinstance(shot, dict):
+                if "small" in shot:
+                    if results_db.analysis.find({
+                        "shots": ObjectId(shot["small"]),
+                    }).count() == 1:
+                        fs.delete(ObjectId(shot["small"]))
+
+                if "original" in shot:
+                    if results_db.analysis.find({
+                        "shots": ObjectId(shot["original"]),
+                    }).count() == 1:
+                        fs.delete(ObjectId(shot["original"]))
+
+                continue
+
             if results_db.analysis.find({"shots": ObjectId(shot)}).count() == 1:
                 fs.delete(ObjectId(shot))
```

**Comment by doomedraven** [comment] 2017-02-11 12:43
thanks, will test in a bit :)

**Comment by doomedraven** [comment] 2017-02-11 13:07
```
Great! :-)
Task deleted, thanks for all the fish.
```

works perfectly

**Comment by jbremer** [comment] 2017-04-04 08:41
This issue has been resolved, thanks!

**Closed by jbremer** 2017-04-04 08:41 UTC

**Comment by eskriett** [comment] 2017-05-25 08:18
Are you sure the fix above actually does as intended?

The shots are now stored in mongo as follows:

```
> db.analysis.findOne({ }, { "shots": 1 })
{
        "_id" : ObjectId("5926727fdcef984e574582aa"),
        "shots" : [
                {
                        "original" : ObjectId("5926727fdcef984e574582a4")
                },
                {
                        "original" : ObjectId("5926727fdcef984e574582a6")
                }
        ]
}
```

The patched code does the following:

```
if "original" in shot:
    if results_db.analysis.find({
        "shots": ObjectId(shot["original"]),
    }).count() == 1:
        fs.delete(ObjectId(shot["original"]))
```

Assuming I'm not misreading, if we do a lookup for `5926727fdcef984e574582a4` using the query used by the code we get:

```
> db.analysis.find({ "shots": ObjectId("5926727fdcef984e574582a4") }).count()
0
```

I think that the query should actually be:
```
> db.analysis.find({ "shots": { $elemMatch: { "original": ObjectId("5926727fdcef984e574582a4") } } }).count()
1
```

or for brevity:

```
db.analysis.find({ "shots.original": ObjectId("5926727fdcef984e574582a4") }).count()
```

Note this is very inefficient, if you have 1000s of analyses this query takes a upwards of a few minutes to complete!!

**Comment by eskriett** [comment] 2017-05-25 08:42
For those wishing to increase the speed of the `/analysis/remove` endpoint, I've found adding a few indexes helps:
```
> db.analysis.createIndex({ "shots.original": 1 })
> db.analysis.createIndex({ "shots.small": 1 })
```

If you've transitioned from legacy cuckoo, then the following is also required:
```
> db.analysis.createIndex({ "shots": 1 })
```

**Comment by eskriett** [comment] 2017-05-25 09:25
While I'm here, an additional improvement to the `/analysis/remove`  would be to return a 404 instead of a 500 if an analysis doesn't exist:

```diff
     if not analyses.count():
-        return view_error(request, "The specified analysis does not exist")
+        return view_error(request, "The specified analysis does not exist", status=404)
```

Useful if you call this endpoint from a script and want to know if there's an actual server error or if the analysis doesn't exist.
