### ISSUE TITLE
Activate OLE objects embedded in Office documents

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1650] opened 2017-06-10 19:02 UTC
These samples require users to double-click on a specific part of the document. This is becoming a common sandbox avoidance technique.

https://blogs.technet.microsoft.com/mmpc/2016/06/14/wheres-the-macro-malware-author-are-now-using-ole-embedding-to-deliver-malicious-files/

 Commercial sandboxes like Joe Sandbox and VXWorks are able to execute these samples, though I have no idea how.

**Comment by jbremer** [comment] 2017-12-04 20:53
Yeah, any tips on how to solve this issue would be great. Duplicate @ #1514.

**Comment by jbremer** [comment] 2018-02-04 13:53
Closing as duplicate of #1514 (and pasting the link there too).

**Closed by jbremer** 2018-02-04 13:53 UTC
