### ISSUE TITLE
Specifying the snapshot in virtualbox.conf breaks the host-agent connection string

### ISSUE THREAD

**Issue by fonyi** [cuckoosandbox/cuckoo#972] opened 2016-06-23 18:37 UTC
I updated the snapshot switch in the virtualbox.conf to snaphot = cuckootest and received the following error. After commenting that line out, the error went away.  Looks like the snaphot name was appended onto the end of the host URL string for some reason. 

2016-06-23 13:15:16,363 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/malware/cuckoo/lib/cuckoo/core/scheduler.py", line 496, in run
    self.launch_analysis()
  File "/home/malware/cuckoo/lib/cuckoo/core/scheduler.py", line 382, in launch_analysis
    self.guest_manage(options)
  File "/home/malware/cuckoo/lib/cuckoo/core/scheduler.py", line 289, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/malware/cuckoo/lib/cuckoo/core/guest.py", line 372, in start_analysis
    r = self.get("/")
  File "/home/malware/cuckoo/lib/cuckoo/core/guest.py", line 281, in get
    return requests.get(url, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/api.py", line 71, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/api.py", line 57, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.56.101%0Asnapshot%20=%20cuckootest', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc0edbdedd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by fonyi** [comment] 2016-06-23 18:38
I am running cuckoo 2.0-dev

**Comment by jbremer** [comment] 2016-06-24 03:32
Please check that you properly emitted a newline.. or like, paste your configuration here on github ;-)

**Comment by fonyi** [comment] 2016-06-24 13:47
I pasted the conf file below. The same issue occurs when I uncomment any variable below the IP address for cuckoo1. 

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui", "sdl" or "headless". Refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = cuckoo1

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
# snapshot = Snapshot1

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
# interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here 
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
# resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
# resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by jbremer** [comment] 2016-06-26 10:39
And you can still reproduce this issue - if so, can you share your exact configuration (as a `zip` file or so) with us?

**Comment by jbremer** [comment] 2017-02-25 11:16
You can uncomment all you want, but there must be no spaces in front of the keywords. Also, for the record, the exception that you showed doesn't match up with the configuration you posted ;-)
Closing this issue as a duplicate of #1085.

**Closed by jbremer** 2017-02-25 11:16 UTC
Labels: Bug (to verify), High Priority
