### ISSUE TITLE
Failing to run cuckoo web

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1520] opened 2017-05-04 09:34 UTC
When trying to run the command `Cuckoo web` I receive the response:
```
c:\python27\python.exe: can't open file 'C:\Python27\Scripts\cuckoo': [Errno 2] No such file or directory
2
```
Also `C:\Python27\Scripts\cuckoo.exe web` and `C:\Python27\Scripts\cuckoo.exe web` both fail too.

Mongod is running & I can run cuckoo just fine, it is only when I put the command web afterwards it breaks. Other commands such as `Cuckoo clean` and `Cuckoo api` work.

I am using Python 2.7.6 64 bit (downgraded from 2.7.13) on Windows 7 64 bit OS.

**Comment by jbremer** [comment] 2017-05-04 09:39
Yes, closing as duplicate of #1424.

**Comment by Waffles-2** [comment] 2017-05-04 09:40
Oh yeah my bad! sorry!

**Closed by jbremer** 2017-05-04 09:39 UTC
