### ISSUE TITLE
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'name' used in key specification without a key length")

### ISSUE THREAD

**Issue by gqqcode** [cuckoosandbox/cuckoo#1197] opened 2016-12-02 06:58 UTC
> I think this is a bug, but I can solve it
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'name' used in key specification without a key length") [SQL: u'\nCREATE TABLE node (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname TEXT NOT NULL, \n\turl TEXT NOT NULL, \n\tmode TEXT NOT NULL, \n\tenabled BOOL NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (name), \n\tCHECK (enabled IN (0, 1))\n)\n\n']

**Comment by jbremer** [comment] 2016-12-02 09:14
Which version of Cuckoo are you running? I believe this has already been fixed!

**Comment by gqqcode** [comment] 2016-12-02 09:53
Cuckoo Sandbox 2.0-rc2，I think mysql variable length string is not set the primary key @jbremer

**Comment by jbremer** [comment] 2016-12-02 09:57
Yes, hmm, I thought that I had changed that a while ago already. It used to be an issue to have a `sqlalchemy`'s `String()` object without providing the length, but now it would appear that `Text()` is not allowed without a length either. To be investigated.

**Comment by gqqcode** [comment] 2016-12-02 10:05
ok

**Comment by MarkusTeufelberger** [comment] 2017-01-05 12:29
The issue is the "unique=True" here: https://github.com/cuckoosandbox/cuckoo/blob/master/distributed/distributed/db.py#L45

Postgres doesn't seem to mind, MySQL however does not like this since "TEXT" can be any size.

**Comment by jbremer** [comment] 2017-01-05 13:01
Thanks for pointing out @MarkusTeufelberger, I was not aware of that! Will see and come up with a proper workaround.

**Comment by MarkusTeufelberger** [comment] 2017-01-12 11:45
Potential duplicate of https://github.com/cuckoosandbox/cuckoo/issues/646

**Comment by jbremer** [comment] 2017-03-05 12:08
This issue has been addressed & resolved, thanks to all involved. Closing this issue, and yes @MarkusTeufelberger, it was indeed a duplicate issue.

**Closed by jbremer** 2017-03-05 12:08 UTC
