### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by darkweaver87** [cuckoosandbox/cuckoo#1164] opened 2016-11-08 09:12 UTC
Hello,

I'm using distributed cuckoo 1.2 on debian jessie with kvm using MySQL as database.
Sometime the analysis fail with the following error when I submit multiple files:

```
Traceback (most recent call last):
  File "/usr/share/cuckoo/lib/cuckoo/core/scheduler.py", line 376, in run
    Database().set_status(self.task.id, TASK_REPORTED)
  File "/usr/share/cuckoo/lib/cuckoo/common/utils.py", line 276, in inner
    return f(self, *args, **kwargs)
  File "/usr/share/cuckoo/lib/cuckoo/core/database.py", line 498, in set_status
    row.status = status
AttributeError: 'NoneType' object has no attribute 'status'
```

It's strange because the task id exists in tasks table.
I tried to cleanup my setup and re-run some analysis but same thing.

When the error occurs, all states of tasks are then not saved and the API answers the task is still running but that's not the case.

Do you have any clue ?

Rémi

**Comment by darkweaver87** [comment] 2016-11-08 15:40
FYI, I added a debug line before the failing line and I seems sqlalchemy doesn't return any row (I mean the session is OK):

```
2016-11-08 15:14:48,674 [lib.cuckoo.core.database] DEBUG: set_status(self, 87, reported), session: <sqlalchemy.orm.session.Session object at 0x7f8619c89550>, row: None
2016-11-08 15:14:48,684 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/share/cuckoo/lib/cuckoo/core/scheduler.py", line 376, in run
    Database().set_status(self.task.id, TASK_REPORTED)
  File "/usr/share/cuckoo/lib/cuckoo/common/utils.py", line 276, in inner
    return f(self, *args, **kwargs)
  File "/usr/share/cuckoo/lib/cuckoo/core/database.py", line 499, in set_status
    row.status = status
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by jbremer** [comment] 2016-11-08 15:43
It would appear that this bug had been resolved a while ago. See also 67696170cd01ad321e41c6efed5659f0288ec92e. Don't forget to update every now and then ;-)

**Comment by jbremer** [comment] 2016-11-08 15:44
Please close the issue if that worked for you.

**Comment by olivierHen** [comment] 2016-11-09 10:41
Hi folks!
I think that I had the same problem, so I tryed the solution you provided @jbremer .
Now I have a problem in the report generation. 

I need to make the file analysis in distributed mode, do you recommand to use the V2.0RC1 ? Even in a production mode ? 

Thank you.

**Comment by jbremer** [comment] 2016-11-09 10:54
Could you share the report generation problem with us? I'd recommend using the latest master (which soon will be `2.0-rc2`) or the Cuckoo Package (#863), which is still beta, but has a lot of further improvements.

**Comment by olivierHen** [comment] 2016-11-10 09:10
Sorry for the delay ... 

So here is the stack trace: 
DEBUG:cuckoo.distributed:file: <open file '/tmp/cuckoo/reports/2/report.json', mode 'rb' at 0x7fe9c61c8ed0>
ERROR:Distributed Cuckoo:Exception on /report/2 [GET]
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
resp = resource(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/flask/views.py", line 84, in view
return self.dispatch_request(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
resp = meth(*args, **kwargs)
File "/usr/share/cuckoo/utils/dist.py", line 540, in get
return json.load(F)
File "/usr/lib/python2.7/json/__init__.py", line 290, in load
**kw)
File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 80415 column 41 (char 3701243) 

The problem is that the report isn't well formed (some values are corrupted )
![reportcuckoo](https://cloud.githubusercontent.com/assets/4465457/20170665/832264a2-a72d-11e6-9c2a-188b3dd932a6.png)

I think I will try the V2.0RC1 ...

**Comment by jbremer** [comment] 2016-11-10 09:11
Which version of Cuckoo are you running there? Cuckoo `1.2` (or older) or cuckoo-modified?

**Comment by olivierHen** [comment] 2016-11-10 09:16
Cuckoo 1.2 with 6769617 fix.

**Comment by jbremer** [comment] 2016-11-10 12:40
Well, Cuckoo 1.2 is quite oudated. Please upgrade to 2.0-rc1 or preferably the latest master branch (which will soon be 2.0-rc2).

**Comment by doomedraven** [comment] 2016-11-10 13:15
i would probably suggest don't use rc1 at all, and just use dev branch ,as in it you have solved a lot of bugs, which people reports here all the time

**Comment by olivierHen** [comment] 2016-11-10 13:37
well ... it's quite embarassing ... how do I manage my production environment, I have to get a stabilized version (which obviously will evolve, but not in the same time as the dev version, isn't it)?

**Comment by doomedraven** [comment] 2016-11-10 13:38
as @jbremer told, dev branch will be rc2, and i use it in production, contains much less bugs than rc1

**Comment by jbremer** [comment] 2016-11-10 13:39
Currently upgrading is still a pain, but with #863 this will be much improved. Please stay tuned ;-)

**Comment by olivierHen** [comment] 2016-11-10 14:01
Ok! Thank you very much guys !

**Comment by jbremer** [comment] 2017-02-25 10:53
Closing this issue as resolved.

**Closed by jbremer** 2017-02-25 10:53 UTC
