### ISSUE TITLE
Analyses of .Zip files runs into error

### ISSUE THREAD

**Issue by L4mbo** [cuckoosandbox/cuckoo#701] opened 2015-12-14 11:30 UTC
Hello there,

I already have Cuckoo installed for about a month now and it has already been very usefull to me. However, after scanning my first .zip file recently, I encountered an error, which caused the analysis to abort. The following error message is shown in the report:

"Analysis failed: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted."

I'm running Cuckoo 1.2 on an Ubuntu 14.04 system using python 2.7. I already tried to change the .zip package to the newest (directly downloaded from cuckoo's website), which unfortunately didn't resolve the error.

Looking forward for any advice!
Kind regards

**Comment by jbremer** [comment] 2015-12-14 14:18
Can you give us more information on the contents of the zip file?

**Comment by L4mbo** [comment] 2015-12-15 08:14
The .zip file I am currently trying to scan only contains a few .pdf files. In addition to that I also tried out some other files like .doc and normal text files, but always ended up with the error mentioned above.

Thanks in advance for help!

**Comment by trenerok** [comment] 2016-04-22 09:34
Hi.
I have the same problem. When I download a zip file to scan . In the process an error is thrown "Error:Analyses failed: The package  "modules.packages.zip" start function raised an error: Unable to execute initial process, analysis aborted"

**Comment by jbremer** [comment] 2016-06-27 10:38
Well, you should definitely update from Cuckoo 1.1, but aside from that this is most likely a duplicate of #471, so closing this issue.

**Closed by jbremer** 2016-06-27 10:38 UTC
Labels: Bug (to verify), Low Priority
