### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tls_multi_factory'

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#870] opened 2016-04-19 13:45 UTC
````
ERROR:modules.processing.network:Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../modules/processing/network.py", line 809, in run
    results.update(p2.run())
  File "/opt/cuckoo/utils/../modules/processing/network.py", line 726, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 85, in process
    self.tcp and self.tcp.process(ts, ip, packet)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 88, in process
    s.process(ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 355, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 285, in state_conn
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 569, in handle
    records, length = dpkt.ssl.tls_multi_factory(sent)
AttributeError: 'module' object has no attribute 'tls_multi_factory'
```

````
sudo pip install -U httpreplay
Requirement already up-to-date: httpreplay in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: dpkt in /usr/local/lib/python2.7/dist-packages (from httpreplay)
Requirement already up-to-date: tlslite-ng in /usr/local/lib/python2.7/dist-packages (from httpreplay)
```

**Comment by jbremer** [comment] 2016-04-19 20:50
Thanks. The issue is that rather than updating `dpkt` to the latest version `pip` seems to be ok with using the one provided by your distribution (going to assume Ubuntu/Debian here). I've pushed `httpreplay` version 0.1.12 which includes the following commit https://github.com/jbremer/httpreplay/commit/637e586238fdc773196b726795a346c8d4a8185a.
I'm confident that updating your local version to 0.1.12 will resolve the issue of using an older version of `dpkt`.
Please let me know if that isn't the case.

**Comment by doomedraven** [comment] 2016-04-19 21:08
@jbremer thanks man for quick patch, i will keep you updated about this

**Comment by gtback** [comment] 2016-04-20 13:15
@doomedraven : I believe the default behavior of pip is to not upgrade dependencies of the package you install with `pip install -U` if they are already satisfied. If you explicitly run `sudo pip install -U dpkt`, pip should install the latest dpkt, in this case probably to `site-packages` as to not interfere with the OS-provided version in `dist-packages`.

Clearly the best approach is for the "depending" package (httpreplay in this case) to be more precise with dependency versions (as @jbremer did with his patch), but hopefully this helps in the future for maintainers who aren't as responsive. :grinning:

**Comment by doomedraven** [comment] 2016-04-20 17:19
@jbremer now it return this :D

````
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../modules/processing/network.py", line 809, in run
    results.update(p2.run())
  File "/opt/cuckoo/utils/../modules/processing/network.py", line 726, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 85, in process
    self.tcp and self.tcp.process(ts, ip, packet)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 88, in process
    s.process(ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 355, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 285, in state_conn
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 585, in handle
    while self.states[self.state](self, s, ts):
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 511, in state_decrypt
    self.tls.decrypt_server(record.type, record.data)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 412, in decrypt_server
    return str(self._recordLayer._decryptThenMAC(record_type, bytearray(buf)))
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 469, in _decryptThenMAC
    assert self._readState.encContext.isBlockCipher
AssertionError
```

**Comment by jbremer** [comment] 2016-04-21 09:17
Yes, I didn't investigate that issue yet. Probably needs some additional code.

**Comment by jbremer** [comment] 2016-04-28 16:00
@doomedraven Can you share `dump.pcap` and `tlsmaster.txt` for that analysis?

**Comment by doomedraven** [comment] 2016-04-28 18:47
i don't have anymore this data, if i will get it for new, i will let you know

**Comment by jbremer** [comment] 2016-04-28 19:24
Fair enough. I'll close this issue for now then as it's unrelated to the original issue here.

**Closed by jbremer** 2016-04-28 19:24 UTC
