### ISSUE TITLE
lssas.exe

### ISSUE THREAD

**Issue by idorosido** [cuckoosandbox/cuckoo#895] opened 2016-05-01 12:07 UTC
Hi,

In Cuckoo 2.0-rc1, I see "lsass.exe" process is being monitored and written into the report, for every analysis I do but for no reason (as I understand) - no activity made by this process and the process isn't belonged to the process tree (wasn't created by the malware process or sub-processes).

I tested it with Win7 and WinXP clients and.
I didn't see this behavior in Cuckoo 1.x versions.

For example you can find the report I uploaded to this link:
https://drive.google.com/file/d/0B2QaTF203vr7dWNJZ3lGU2tTUW8/view?usp=sharing

Is it a bug ? 

Thanks,
Ido

**Comment by jbremer** [comment] 2016-05-01 12:49
It's not a bug, please also read the following blogpost ;-) http://jbremer.org/mitm/

**Comment by jbremer** [comment] 2016-05-02 13:10
Going to close this as intended behavior - for extracting TLS Master Secrets - please feel free to re-open or create a new issue if you have any more questions ;-)

**Closed by jbremer** 2016-05-02 13:10 UTC

**Comment by y-oyama** [comment] 2018-05-27 22:05
I opened a new issue #2280, which has been solved.
