### ISSUE TITLE
Several AJAX calls don't end in a slash

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cuckoosandbox/cuckoo#1391] opened 2017-04-11 09:23 UTC
This leads to Django redirecting requests (e.g. calls to [domain]/cuckoo/api/status instead of [domain]/cuckoo/api/status/) and caused a few troubles when running behind an https proxy.

Especially the presubmit call was a bit confusing, when it got rejected silently by the browser. Please look through your AJAX calls and append slashes, if necessary. You can also disable APPEND_SLASH in django and look for 404 errors to find bad calls.

**Comment by jbremer** [comment] 2017-04-11 09:24
Thanks! Actually our plan was to get rid of all trailing slashes, but one thing at a time. We'll be investigating further in a bit - if you have additional URLs that give you errors, do let us know.

**Comment by MarkusTeufelberger** [comment] 2017-04-11 09:31
analysis/[number]/summary

**Comment by jbremer** [comment] 2017-04-12 00:16
@MarkusTeufelberger I've put up an alpha release, installable through `pip install cuckoo==2.0.1a3`, that includes a start on getting rid of the requirement for trailing slashes. Please feel free to try it out.
Re-reading your message, the presubmit part is actually kind of intended behavior at the moment. I'll have to see if it's feasible to properly change that.

**Comment by jbremer** [comment] 2017-04-21 01:27
I guess I'll be closing this issue, provided no new URLs have popped up since the initial ones have been fixed. Feel free to reopen or create a new issue once you find more of 'em, though. Thanks!

**Closed by jbremer** 2017-04-21 01:27 UTC

**Comment by MarkusTeufelberger** [comment] 2017-04-21 08:12
As I said, just disable APPEND_SLASH in Django and you'll get 404s instead of forwards, making it much easier for you to find this.

**Comment by jbremer** [comment] 2017-04-21 09:15
Yes, you're right. I've added it to my local configuration and will be pushing out additional improvements here and there as I find 'em. Thanks again.
