### ISSUE TITLE
Web interface unable to submit sample

### ISSUE THREAD

**Issue by anuclear** [cuckoosandbox/cuckoo#1423] opened 2017-04-18 08:53 UTC
Installed the latest version of cuckoo referring to https://cuckoo.sh/docs/index.html.

Submitting sample via standard or WUSGI+ngnix web gui with "submit file for analysis button" but nothing happens. Here are the web logs:

[17/Apr/2017 22:10:18] "GET /static/images/next.png HTTP/1.1" 200 1350
[17/Apr/2017 22:10:18] "GET /static/images/close.png HTTP/1.1" 200 280
[17/Apr/2017 22:10:18] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
[17/Apr/2017 22:10:18] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 200 13348
[17/Apr/2017 22:10:18] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 200 13308
[17/Apr/2017 22:10:18] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 13
[17/Apr/2017 22:10:19] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[17/Apr/2017 22:10:19] "GET /cuckoo/api/status HTTP/1.1" 200 504
[17/Apr/2017 22:10:25] "POST / HTTP/1.1" 405 0
[17/Apr/2017 22:10:25] "GET /favicon.ico HTTP/1.1" 404 17130
[17/Apr/2017 22:10:25] "GET /favicon.ico HTTP/1.1" 404 17130
[17/Apr/2017 22:10:34] "GET / HTTP/1.1" 200 21964
[17/Apr/2017 22:10:35] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Apr/2017 22:10:35] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 13
[17/Apr/2017 22:11:20] "POST / HTTP/1.1" 405 0

**Comment by doomedraven** [comment] 2017-04-18 08:54
you getting 405 error, start cuckoo web as `cuckoo web -H 0.0.0.0 -p 8000` to see what is wrong, or see logs of uwsgi

**Comment by anuclear** [comment] 2017-04-18 12:31
From "/var/log/uwsgi/app/cuckoo-web.log" I see 200 OK

[pid: 1424|app: 0|req: 4/19] 192.168.234.1 () {50 vars in 920 bytes} [Tue Apr 18 04:22:36 2017] POST / => generated 0 bytes in 21 msecs (HTTP/1.1 405) 10 headers in 286 bytes (2 switches on core 0)

**Comment by doomedraven** [comment] 2017-04-18 12:32
but another log `[17/Apr/2017 22:10:25] "POST / HTTP/1.1" 405 0` so debug where it happens

**Comment by jbremer** [comment] 2017-04-18 12:33
If you run `cuckoo web` manually you might be able to see an exception or so. Or do the `uwsgi` logs have those as well?

**Comment by anuclear** [comment] 2017-04-18 12:48
The thing is that I have the same behavior "uwsgi" and "cuckoo web".

**uwsgi:**

sudo tail /var/log/uwsgi/app/cuckoo-web.log -f
Tue Apr 18 05:03:34 2017 - Python main interpreter initialized at 0x131f690
Tue Apr 18 05:03:34 2017 - your server socket listen backlog is limited to 100 connections
Tue Apr 18 05:03:34 2017 - your mercy for graceful operations on workers is 60 seconds
Tue Apr 18 05:03:34 2017 - mapped 218376 bytes (213 KB) for 2 cores
Tue Apr 18 05:03:34 2017 - *** Operational MODE: preforking ***
Tue Apr 18 05:03:36 2017 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x131f690 pid: 2315 (default app)
Tue Apr 18 05:03:36 2017 - *** uWSGI is running in multiple interpreter mode ***
Tue Apr 18 05:03:36 2017 - spawned uWSGI master process (pid: 2315)
Tue Apr 18 05:03:36 2017 - spawned uWSGI worker 1 (pid: 2332, cores: 1)
Tue Apr 18 05:03:36 2017 - spawned uWSGI worker 2 (pid: 2333, cores: 1)
[pid: 2332|app: 0|req: 1/1] 192.168.234.1 () {44 vars in 679 bytes} [Tue Apr 18 05:03:56 2017] GET / => generated 21964 bytes in 144 msecs (HTTP/1.1 200) 11 headers in 388 bytes (1 switches on core 0)
[pid: 2333|app: 0|req: 1/2] 192.168.234.1 () {50 vars in 843 bytes} [Tue Apr 18 05:03:56 2017] POST /analysis/api/tasks/recent/ => generated 13 bytes in 102 msecs (HTTP/1.1 200) 9 headers in 244 bytes (1 switches on core 0)
[pid: 2332|app: 0|req: 2/3] 192.168.234.1 () {46 vars in 701 bytes} [Tue Apr 18 05:03:56 2017] GET /cuckoo/api/status => generated 503 bytes in 251 msecs (HTTP/1.1 200) 9 headers in 244 bytes (1 switches on core 0)
[pid: 2333|app: 0|req: 2/4] 192.168.234.1 () {50 vars in 920 bytes} [Tue Apr 18 05:04:03 2017] POST / => generated 0 bytes in 2 msecs (HTTP/1.1 405) 10 headers in 286 bytes (1 switches on core 0)

**cuckoo web**

cuckoo web -H 0.0.0.0 -p 8080
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2017 - 04:59:05
Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[18/Apr/2017 04:59:14] "GET / HTTP/1.1" 200 21964
[18/Apr/2017 04:59:14] "GET /static/css/main.css HTTP/1.1" 304 0
[18/Apr/2017 04:59:14] "GET /static/js/vendor.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:14] "GET /static/css/vendor.css HTTP/1.1" 304 0
[18/Apr/2017 04:59:14] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:14] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:14] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/images/close.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/images/loading.gif HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/images/next.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "GET /static/images/prev.png HTTP/1.1" 304 0
[18/Apr/2017 04:59:15] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 13
[18/Apr/2017 04:59:15] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[18/Apr/2017 04:59:16] "GET /cuckoo/api/status HTTP/1.1" 200 502
[18/Apr/2017 04:59:22] "POST / HTTP/1.1" 405 0

**Comment by jbremer** [comment] 2017-04-18 12:49
Thanks. Eh, yeah, I think the issue is that the URI for submitting files isn't picked up properly.
Which browser are you using?

**Comment by anuclear** [comment] 2017-04-18 14:38
Firefox 52.0.2 (32-bit). By the way I have the following error trying to start "cuckoo -d"

2017-04-18 06:23:39,501 [cuckoo.machinery.physical] DEBUG: Received unknown exception: <ProtocolError for 192.168.56.122:8000/RPC2: 404 Not Found>.
CuckooCriticalError: Error initializing machines: Unknown error occurred trying to obtain the status of physical machine physical1. Please turn it on and check the Cuckoo Agent.

**Comment by anuclear** [comment] 2017-04-18 15:01
checks using telnet returns:

```
telnet 192.168.56.122
Trying 192.168.56.122...
telnet: Unable to connect to remote host: Connection refused
gamba@devastator:~/.cuckoo$ telnet 192.168.56.122 8000
Trying 192.168.56.122...
Connected to 192.168.56.122.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 200 OK
Server: Cuckoo Agent Python/2.7.13
Date: Tue, 18 Apr 2017 15:00:55 GMT

{"message": "Cuckoo Agent!", "version": "0.7", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}Connection closed by foreign host.
```

**Comment by yeejay** [comment] 2017-04-18 23:31
Just wanted to say that I'm getting the same issue.  I'm using Firefox ESR 38.3.0 on RHEL 7.  The regular submit and import buttons are fine though.

**Comment by gra55h0pp3r** [comment] 2017-04-19 15:10
I'm getting the same error when I try clicking the submit file for analysis from the home page. If I click the submit button, then I can add a file it will work. I'm trying all the different options and when I try to specify the specific VMWare image I want it to run against it doesn't do anything. It just back to the home submit page and I try to select the file again and specify the vm again and again it doesn't work. Now, if I don't select a specific VM, then it will work and I can see it in the cuckoo debug log (cuckoo -d) that the vm started and etc...

**Comment by jbremer** [comment] 2017-04-19 15:11
We're about to publish a bugfix release, stay tuned ;-)

**Comment by jbremer** [comment] 2017-04-20 13:52
@anuclear @yeejay @gra55h0pp3r We've just released an alpha release, which you can get with `pip install cuckoo==2.0.2a2`, containing a fix for the issue here. Please let me know if it also works on your side. This will be part of the upcoming `2.0.2` release.

**Comment by jbremer** [comment] 2017-04-28 23:42
Closing issue as resolved. Thanks as usual.

**Closed by jbremer** 2017-04-28 23:42 UTC

**Comment by NewSystemGames** [comment] 2019-07-19 17:53
same issue
