### ISSUE TITLE
Web Deployment (nginx + uwsgi)

### ISSUE THREAD

**Issue by bcallaughan** [cuckoosandbox/cuckoo#1762] opened 2017-08-09 06:26 UTC
I have used the manual to deploy nginx + uqsgi but am getting 502 Bad Gateway when attempting to load the webUI, it looks to be a permissions issue but I can't work out what I am missing.

I have checked the logs and can see the following error in the nginx error.log
2017/08/09 16:11:57 [crit] 6241#6241: *8 connect() to unix:/run/uwsgi/app/cuckoo-web/socket failed **(13: Permission denied)** while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-web/socket:", host: "127.0.0.1:8000"

I have confirmed the www-data user is in the cuckoo group via sudo adduser www-data cuckoo, the user brett is also in the cuckoo group.

Both nginx and wqsgi are running and have been reloaded/restarted:

**uwsgi config**
cuckoo-web.ini
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = brett
gid = brett
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/brett/.cuckoo

**cuckoo-web nginx config:**
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
    listen localhost:8000;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
    }
}

**Comment by bcallaughan** [comment] 2017-08-10 21:57
Resolved with https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27
including SSL and Password Protect

**Comment by jbremer** [comment] 2017-09-09 11:25
Ehm, can you take a look at the network traffic generated by your browser? Any requests that seem to be failing? Any exception in the `uwsgi` logs regarding the Cuckoo Web Interface?

**Comment by jbremer** [comment] 2017-12-04 20:09
Closing issue for lack of additional information. Please reopen if you have more information for us. Seems that resolving permission issues should do the trick. Thanks!

**Closed by jbremer** 2017-12-04 20:09 UTC

**Comment by hfakar** [comment] 2018-10-08 08:03
Hello I recently have encountered this issue. 
![image](https://user-images.githubusercontent.com/13640312/46597639-b5239980-cae9-11e8-8ed7-8da4e859f358.png)
Why dont i have antything for the uwsgi logs? 
And i get the same error as above.

**Comment by doomedraven** [comment] 2018-10-08 09:36
are you sure what uwsgi running?

**Comment by hfakar** [comment] 2018-10-09 14:13
Yes infact it is running. 

![image](https://user-images.githubusercontent.com/13640312/46674874-e4b7cc00-cbe5-11e8-88d6-10ce193f5ef4.png)

The interesting thing is why are these configurations are different? You will see that the uid and guid's are different. This might be the cause for the Permission denied fault on the socket.
What did i do wrong?

![image](https://user-images.githubusercontent.com/13640312/46675164-79bac500-cbe6-11e8-9651-98adf12c52c5.png)

**Comment by doomedraven** [comment] 2018-10-09 14:14
check the socket permission as it not started with cuckoo user, so custom user can give some problems

**Comment by hfakar** [comment] 2018-10-09 15:14
The permission of the socket file:

![image](https://user-images.githubusercontent.com/13640312/46679180-184b2400-cbef-11e8-9796-790c9f9c97b8.png)

What can i do next?

**Comment by doomedraven** [comment] 2018-10-09 16:00
Change uwsgi config and run uwsgi as standalone uwsgi —ini config

**Comment by hfakar** [comment] 2018-10-10 06:32
What do you want me to change and where is this other uwsgi config?

**Comment by doomedraven** [comment] 2018-10-10 07:06
can you do search in issues? i posted config in one of them, there was few issues like this one

**Comment by hfakar** [comment] 2018-10-10 08:56
I did I found this one here: #2261 and my config is the same.

`hfakar@yxxxxx-xxxx:~$ cat /etc/uwsgi/apps-available/cuckoo-web.ini
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = hfakar
gid = hfakar
static-map = /static=/home/hfakar/.local/lib/python2.7/site-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/hfakar/.cuckoo
`

And this is the output of uwsgi:
`hfakar@xxxxxxxx:~$ sudo uwsgi --ini /etc/uwsgi/apps-enabled/cuckoo-web.ini -s  unix:/run/uwsgi/app/cuckoo-web/socket
[uWSGI] getting INI configuration from /etc/uwsgi/apps-enabled/cuckoo-web.ini
[uwsgi-static] added mapping for /static => /home/hfakar/.local/lib/python2.7/site-packages/cuckoo/web/static
*** Starting uWSGI 2.0.15-debian (64bit) on [Wed Oct 10 08:50:05 2018] ***
compiled with version: 7.3.0 on 28 September 2018 15:41:15
os: Linux-4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018
nodename: xxxxxxxx
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/hfakar
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
setgid() to 1000
set additional group 4 (adm)
set additional group 24 (cdrom)
set additional group 27 (sudo)
set additional group 30 (dip)
set additional group 46 (plugdev)
set additional group 108 (lxd)
setuid() to 1000
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 23606
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address unix:/run/uwsgi/app/cuckoo-web/socket fd 3
dropping root privileges after socket binding
Python version: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)  [GCC 7.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ddf3291770
dropping root privileges after plugin initialization
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ddf3291770 pid: 25722 (default app)
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 25722, cores: 1)`

This is the error Log of nginx:
`2018/10/10 08:50:30 [crit] 25788#25788: *2 connect() to unix:/run/uwsgi/app/cuckoo-web/socket failed (2: No such file or directory) while connecting to upstream, client: 10.2.208.31, server: xxxxxxxx, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-web/socket:", host: "xxxxxxxx", referrer: "https://xxxxxxxx/"
`

**Comment by doomedraven** [comment] 2018-10-10 08:58
no, that is classical what cuckoo gens

```
[uwsgi]
    plugins = python
    callable = application
    ;change this patch if is different
    chdir = /opt/cuckoo/utils
    master = true
    mount = /=api.py
    processes = 5
    manage-script-name = true
    socket = 0.0.0.0:8090
    pidfile = /tmp/api.pid
    ; if you will use with nginx, comment next line
    protocol=http
    enable-threads = true
    lazy-apps = true
    timeout = 600
    chmod-socket = 664
    chown-socket = cuckoo:cuckoo
    gui = cuckoo
    uid = cuckoo
```

see socket ` socket = 0.0.0.0:8090` you need adjust your conf, bcz this for old version, but can be running as `uwsgi --ini config.ini`

**Comment by hfakar** [comment] 2018-10-10 09:11
Which  directory should be chdir = 
I dont have a utils directory

**Comment by doomedraven** [comment] 2018-10-10 09:12
try something like

```
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = hfakar
gid = hfakar
static-map = /static=/home/hfakar/.local/lib/python2.7/site-packages/cuckoo/web/static
#If you're getting errors about the PYTHON_EGG_CACHE, then
#uncomment the following line and add some path that is
#writable from the defined user.
#env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/hfakar/.cuckoo
socket = 0.0.0.0:8090
protocol=http
```


some args can be depricated, see officual uwsgi docu for that, but should be something like that, i have added just last 2 args

**Comment by hfakar** [comment] 2018-10-10 10:46
I am running nginx in front? Should i change the socket or upstream on nginx.conf?

Because it doesnt change anything. Uwsgi runs but I still get 502 on web.

The thing is I already had a good installation and cuckoo was up and running. Somebody uploaded a word file and it crashed. Couldnt get it up since then.

**Comment by doomedraven** [comment] 2018-10-10 10:47
no as i told first try to run uwsgi standalone without nothing else, so in that way you can go step by step and debug your issues

**Comment by hfakar** [comment] 2018-10-10 10:57
I did that but as i said it didnt change anything. I still get 502. Nothing changed on nginx and uwsgi logs

**Comment by hfakar** [comment] 2018-10-10 11:09
It went up with the http only. What next? Should I connect to nginx? When I do how do I listen on the uwsgi side?

**Comment by doomedraven** [comment] 2018-10-10 11:16
try connect with nginx, and see if you can get it in http on nginx, so then you will ahve working http with uwsgi+nginx

**Comment by hfakar** [comment] 2018-10-10 15:05
The problem was the socket permissions. However it was because the cuckoo rooter groups and using different user on that messed uwsgi up. Thanks for your help.

**Comment by doomedraven** [comment] 2018-10-10 15:06
that already was in one of the issues ;) you have fix there if i remember correctly you need to add cuckoo to www-data or something like that, check issues for exact fix

**Comment by Ma780aPar** [comment] 2019-04-30 12:59
Guys  you found a solution, please share it. The problem is common for all. My cuckoo installation does not work with uwsgi and nginx as well.
