### ISSUE TITLE
Failed to generate JSON report

### ISSUE THREAD

**Issue by jjj1987** [cuckoosandbox/cuckoo#918] opened 2016-05-13 05:51 UTC
Hello,
I'm running Cuckoo 2.0-rc1 with android VMs, using avd.
I'm running Cuckoo 2.0-rc1 for URL analysis; I seem to be running into an error with the MongoDB reporting.When I submit url on Windows XP VMs and Virtualbox,it have a same error.
2016-05-12 23:14:27,354 [lib.cuckoo.core.plugins] WARNING: The reporting module "JsonDump" returned the following error: Failed to generate JSON report: set([]) is not JSON serializable
2016-05-12 23:14:27,828 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo20/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/cuckoo20/cuckoo/modules/reporting/mongodb.py", line 224, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2177, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 519, in _insert_one
    check_keys, acknowledged, concern, False, self.codec_options)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 450, in _legacy_write
    rqst_id, msg, max_size = func(*args)
InvalidDocument: Cannot encode object: set([])
Is anyone else experiencing this issue?
Thanks

**Comment by doomedraven** [comment] 2016-05-14 23:34
i had that error on rc1, don't remember how i solved that, move to dev it has a lot of fixes which presented in rc1

**Comment by jbremer** [comment] 2016-05-16 07:53
This is an error specific android analysis, I'll have to check what values have to be updated to fix this.

**Comment by jjj1987** [comment] 2016-05-16 08:00
@jbremer , only url analysis,I have this error.  When I submit file,I didn't encounter this problem.
I didn't develop any  custom processing modules.
Thanks

**Comment by jbremer** [comment] 2016-05-16 08:01
Could you please share a zip of the entire analysis?

**Comment by jjj1987** [comment] 2016-05-16 08:24
sorry,I upload the entire analysis result in zip format,but failed.
Is there any other way?

**Comment by BlackyFox** [comment] 2016-07-25 14:00
Hi, I have a similar issue with y cuckoo instance (2.0-rc1).
It happens with every url analysis actually...

```
WARNING: The reporting module "JsonDump" returned the following error: Failed to generate JSON report: set([]) is not JSON serializable.
ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
    File "/home/cuckoo/cuckoo/lib/core/plugin.py", line 507, in process
        current.run(self.results)
    File "/home/cuckoo/cuckoo/modules/reporting/mongodb.py", line 224, in run
        self.db.analysis.save(report)
    File "/usr/local/lib/python2.7/dist-packages/pymongi/collection.py", line 1903, in save
        check_keys, manipulate, write_concern)
    File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
        self.codec_options, sock_info)
InvalidDocument: Cannot encore object: set([])
```

**Comment by jbremer** [comment] 2016-07-27 04:14
@jjj1987 @BlackyFox Could you please share the entire analysis directory as well as your `conf/processing.conf` file?

**Comment by BlackyFox** [comment] 2016-08-01 08:50
@jbremer Of course. How do you want me to send it to you? Here? By email?

**Comment by jbremer** [comment] 2016-08-01 08:53
Here would be easiest :-) But if that fails, `jbr@cuckoo.sh` is fine as well.

**Comment by BlackyFox** [comment] 2016-08-01 09:17
[Failed_analysis.tar.gz](https://github.com/cuckoosandbox/cuckoo/files/393347/Failed_analysis.tar.gz)
Here you are :-)

**Comment by BlackyFox** [comment] 2016-08-05 13:31
Sorry to bother, but have you found anything with this archive?

**Comment by jbremer** [comment] 2016-08-05 17:15
Unfortunately I can't reproduce this against the latest development version - and for some reason `2.0-rc1` is giving all kinds of unrelated errors at the moment. So, please upgrade.. ;-)

**Comment by jbremer** [comment] 2016-11-10 13:14
Closing as resolved'ish.

**Closed by jbremer** 2016-11-10 13:14 UTC
