### ISSUE TITLE
Export to pdf

### ISSUE THREAD

**Issue by Neodyn** [cuckoosandbox/cuckoo#1871] opened 2017-09-29 11:19 UTC
I want to use the option export to pdf. This is configured in reporting.conf
`[singlefile]
enabled = yes
html = no
pdf = yes
`
But after analyze the following error occurs:
`[weasyprint] ERROR: Failed to load font at "data:application/font-woff2;charset=utf-8;base64,`

Weasyprint has been installed with:
`virtualenv ./venv
. ./venv/bin/activate
pip install WeasyPrint`

How can i fix this error?

**Comment by Marcus-D** [comment] 2017-10-01 05:15
@Neodyn, I also had that issue. Here's I solved it.
https://github.com/cuckoosandbox/cuckoo/issues/1868

**Comment by jbremer** [comment] 2017-10-21 10:15
Ah, thanks @Marcus-D. Closing this as duplicate of #1868.

**Closed by jbremer** 2017-10-21 10:15 UTC
