### ISSUE TITLE
Problem in submitting a binary

### ISSUE THREAD

**Issue by ghibbster** [cuckoosandbox/cuckoo#741] opened 2016-01-29 16:10 UTC
**Hello,
I have followed all the installation steps provided on the website. 
I have tried to scan a binary file, getting this error:**

npellegrino@nino:~/cuckoo$ python cuckoo.py

_____________________________________/\/_______________________________
__/\/\/\/_/\/__/\/____/\/\/\/__/\/__/\/____/\/\/______/\/\/___
/\/_______/\/__/\/__/\/________/\/\/\/____/\/__/\/__/\/__/\/_
/\/_______/\/__/\/__/\/________/\/\/\/____/\/__/\/__/\/__/\/_
/\/\/\/_/\/\/\/____/\/\/\/__/\/__/\/____/\/\/______/\/\/___

Cuckoo Sandbox 2.0-dev
www.cuckoosandbox.org
Copyright (c) 2010-2015

Checking for updates...
Outdated! Cuckoo Sandbox version 2.0-rc1 is available now.
2016-01-29 16:29:26,511 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-01-29 16:29:27,034 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-01-29 16:29:27,042 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-01-29 16:30:30,767 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "XXXX.exe" (task #1, options "")
2016-01-29 16:30:30,811 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine CUCKOO (label=CUCKOO)
2016-01-29 16:30:30,817 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 11736 (interface=vboxnet0, host=192.168.56.101, pcap=/home/npellegrino/cuckoo/storage/analyses/1/dump.pcap)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 65535 bytes
2016-01-29 16:30:33,214 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=CUCKOO, ip=192.168.56.101)
5 packets captured
7 packets received by filter
0 packets dropped by kernel
2016-01-29 16:30:41,000 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
File "/home/npellegrino/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
self.launch_analysis()
File "/home/npellegrino/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
self.guest_manage(options)
File "/home/npellegrino/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
guest.start_analysis(options, monitor)
File "/home/npellegrino/cuckoo/lib/cuckoo/core/guest.py", line 389, in start_analysis
self.old.start_analysis(options, monitor)
File "/home/npellegrino/cuckoo/lib/cuckoo/core/guest.py", line 155, in start_analysis
self.upload_analyzer(monitor)
File "/home/npellegrino/cuckoo/lib/cuckoo/core/guest.py", line 127, in upload_analyzer
self.server.add_analyzer(data)
File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in call
return self.send(self.__name, args)
File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
verbose=self.__verbose
File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
return self.parse_response(response)
File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
return u.close()
File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
raise Fault(**self._stack[0])
Fault: :ZipFile instance has no attribute '__exit'">

**Any ideas on how can I get that fixed please ?
Thank you very much**

**Comment by jekil** [comment] 2016-01-29 22:13
Are you using python 2.7 on virtual machine?
Could you please give more details about your setup and the sample you are analying?

**Comment by ghibbster** [comment] 2016-01-30 17:11
Yes,
I'm using python 2.7 on both the virtual machine and the host.

Which kind of details do you need about the setup (which files)?

About the binary, it's a malware sample.

2016-01-29 23:13 GMT+01:00 Alessandro Tanasi <notifications@github.com>:

**Comment by jbremer** [comment] 2016-02-07 03:35
That's a pretty messed up issue / traceback. Are you able to reproduce it? Can you tell us more about your environment (all packages and versions etc on the host)?

**Comment by ghibbster** [comment] 2016-02-08 09:12
I'm running an Ubuntu 14.04 64 bit on the host.
I've attached a list of all the installed packages.

About the issue, I can reproduce it running other samples (still .exe files) .

Thank you for your help anyway.

[packages.txt](https://github.com/cuckoosandbox/cuckoo/files/121322/packages.txt)

**Comment by jbremer** [comment] 2016-02-09 19:09
Hmm, could you try `pip install -r requirements.txt` and then restart Cuckoo? That file contains versions of the various Python libraries that we know are properly supported (and close to the latest).

**Comment by ghibbster** [comment] 2016-02-10 09:47
It crushes when trying to install "http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile"

Downloading http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz (57kB)
    100% |████████████████████████████████| 57kB 396kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f_anblct/pefile/setup.py", line 5
        except ImportError, excp:
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f_anblct/pefile

**Comment by jbremer** [comment] 2016-02-10 10:09
Never seen that error before.. implies that the `setup.py` has invalid Python syntax, but this exact package is definitely installed on other boxes that we manage. Anyway, can you remove the `pefile` entry from the `requirements.txt` file? It's optional anyway. Then try again.

**Comment by ghibbster** [comment] 2016-02-10 10:37
Well ... it crushes again trying to compile cffi.

creating build/temp.linux-x86_64-3.4/c
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
    c/_cffi_backend.c:2:20: fatal error: Python.h: File o directory non esistente
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o_tjp4t5/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-73u8gowu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-o_tjp4t5/cffi

I have that header, inded:

~/cuckoo$ apt-file search --regexp '/Python.h$'
libpython2.7-dbg: /usr/include/python2.7_d/Python.h
libpython2.7-dev: /usr/include/python2.7/Python.h
libpython3.4-dbg: /usr/include/python3.4dm/Python.h
libpython3.4-dev: /usr/include/python3.4m/Python.h
pypy-dev: /usr/lib/pypy/include/Python.h

**Comment by jbremer** [comment] 2016-02-10 10:40
Well, for that please refer to the documentation. `apt-get install python-dev libffi-dev`

**Comment by ghibbster** [comment] 2016-02-10 10:53
but I have both of them installed, and nothing changes

**Comment by ghibbster** [comment] 2016-02-10 10:55
apt-get install python-dev libffi-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
python-dev è già alla versione più recente. (// already up to the most recent version)
libffi-dev è già alla versione più recente. (already up to the most recent version)
0 aggiornati, 0 installati, 0 da rimuovere e 112 non aggiornati.

**Comment by jekil** [comment] 2016-02-11 22:27
I will suggest to debug issues for each dependecy, then move to cuckoo.
BTW it is really weird, usually it is pretty much straightforward to setup everything, I will also suggest to check your system.

**Comment by gtback** [comment] 2016-02-17 15:19
Hi @ghibbster: All of the errors I'm seeing seem to suggest that you're running Python 3. The package list you attached includes `libpython2.7-dev` but not `libpython3.4-dev`, which could explain the "Python.h not found" error if your build command (`python setup.py install` or `pip install`) is actually invoking the Python 3 versions. Also, the `SyntaxError` on the line `except ImportError, excp:` suggests Python 3, since that syntax for catching exceptions was removed in Python 3. 

Try running `which python`, `which pip` and `python --version` and reporting the results. If you can adjust your PATH or other environment settings so that you're using Python 2, I believe the issues should go away.

**Comment by ghibbster** [comment] 2016-02-18 12:28
$ which python
/usr/bin/python
$ which pip
/usr/local/bin/pip
$ python --version
Python 2.7.6

**Comment by gtback** [comment] 2016-02-18 14:10
Hmm, that's really strange then. I can't explain it. Sorry :frowning:

**Comment by jbremer** [comment] 2016-02-18 14:13
Given three people have no idea what's going wrong (myself included), I suggest you either reinstall your machine or use a different one for testing out Cuckoo ;-)

**Comment by jbremer** [comment] 2016-03-03 00:21
Closing this issue as an impossible issue related to your system.

**Closed by jbremer** 2016-03-03 00:21 UTC
Labels: Bug (to verify)

**Comment by microbot007** [comment] 2016-11-01 13:04
I am configuring cuckoo and followed the installation guide properly  and also configured virtual.conf but still at end on running cuckoo.py i m getting following errors:

2016-11-01 18:24:34,840 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-11-01 18:24:35,095 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine win7 are missing: Option win7 is not found in configuration, error: Config instance has no attribute 'win7'
2016-11-01 18:24:35,674 [root] CRITICAL: CuckooCriticalError: No machines available.

**Comment by doomedraven** [comment] 2016-11-01 13:36
you configured your virtual box wrong
no win7 exits

**Comment by microbot007** [comment] 2016-11-01 14:49
@doomedraven : this is my virtualbox.conf,
i have done it according to guide..

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui", "sdl" or "headless". Refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = win7

#[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = win7

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = Windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 10.0.0.17

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = snapshot1

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
 interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
# resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
# resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = win7,32_bit,acrobat_reader_6

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 10.0.0.16
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by jbremer** [comment] 2016-11-01 14:52
Feel free to show us where in the guide it mentioned to comment out `[cuckoo1]`, which, for your case, should be `[win7]`.

**Comment by microbot007** [comment] 2016-11-01 14:57
Sorry, later i corrected [cuckoo1] to [win7] and uncommented.
but then i m getting below error:

2016-11-01 20:21:08,927 [lib.cuckoo.core.scheduler] INFO: Using
"virtualbox" as machine manager
2016-11-01 20:22:21,981 [root] CRITICAL: CuckooCriticalError: Please update
your configuration. Unable to shut 'win7' down or find the machine in its
proper state: Timeout hit while for machine win7 to change status


Best Regards

Sonali Tyagi
M.Tech (ISM)
(+91 9582952543)
*TnP Coordinator*
*ISEA Student Member*

*DeitY, Govt. of India*
https://in.linkedin.com/in/sonali-tyagi-92309798

**Comment by doomedraven** [comment] 2016-11-01 15:05
but did you restart cuckoo.py? also can you provide screen of vbox manager with vm or execute in cli `vboxmanage list vms`

**Comment by microbot007** [comment] 2016-11-01 15:08
yes i restart cuckoo.py..
the output is of above command is : "win7" {e88bb6e8-4e5d-44bd-9b34-b9b06d1271e6}

**Comment by doomedraven** [comment] 2016-11-01 15:10
`Unable to shut 'win7' down or find the machine in its
proper state: Timeout hit while for machine win7 to change status`

as this said, probably wrong state of snapshot? can you start vm manually and execute from host `curl vm_ip:8000` you should get error 50x which mean communication with agent works fine, can you verify that?

**Comment by microbot007** [comment] 2016-11-01 15:25
I ran this command and getting:

Curl:(7) Failed to connect to 10.0.0.20 port 8000: connection refused

**Comment by doomedraven** [comment] 2016-11-01 15:28
so basically host cuckoo can't speak with vm, that can be related to:
1. vm firewall
2. agent is not running(must be under admin)
3. external firewall

**Comment by microbot007** [comment] 2016-11-01 15:43
1.firewall is turned off.
2. agent is added in startup
3.should i turn off host firewall too?

**Comment by doomedraven** [comment] 2016-11-01 16:05
Is added but something not allowing connection, as you saw curl result, try shutdown host firewall, and if that is a case, you will need allow communication to port 8000 in vms and 2042 on host

Best regards
Andriy

**Comment by microbot007** [comment] 2016-11-01 16:39
I tried by doing host firewall off. And yes connection is not getting set
between host and guest coz I can ping guest from host but vice versa not
possible.

**Comment by doomedraven** [comment] 2016-11-01 16:45
So is your setup problem, not cuckoo

**Comment by microbot007** [comment] 2016-11-02 05:49
Now both are pinging to each other.
even telnet "vm_ip" 8000 is working too.

but still on running sudo python cuckoo.py i m getting::

CuckooCriticalError: Please update your configuration. Unable to shut
'win7' down or find the machine in its proper state: Timeout hit while for
machine win7 to change status.

please help.

**Comment by doomedraven** [comment] 2016-11-02 06:00
Did you take new snapshot after solve issue? In running state?

Best regards
Andriy

**Comment by microbot007** [comment] 2016-11-02 07:10
yes i did that too.

Please help.

Best Regards

Sonali Tyagi
M.Tech (ISM)
(+91 9582952543)
*TnP Coordinator*
*ISEA Student Member*

*DeitY, Govt. of India*
https://in.linkedin.com/in/sonali-tyagi-92309798

**Comment by doomedraven** [comment] 2016-11-02 07:11
you must investigate what is wrong with your vm as error says

`CuckooCriticalError: Please update your configuration. Unable to shut
'win7' down or find the machine in its proper state`

**Comment by microbot007** [comment] 2016-11-03 05:52
@doomedraven : i got the problem solved. it was an issue with vm actually. i needed to run the vm through sudo. then it worked.
Thanks for help!
