### ISSUE TITLE
Failed injection on guest

### ISSUE THREAD

**Issue by Nwinternights** [cuckoosandbox/cuckoo#1740] opened 2017-07-29 23:22 UTC
Hi,
Submitting this sample c72673c960de2373ebfda157895e2a17 (https://malwr.com/analysis/ZmZiYWUwMDY4MTBkNDY4OWFiZTMxZjM5NTRmMGY2OGU/) the analysis fails because something goes wrong with behavioral analysis.
here is some infos maybe that can be useful 
![screenshot from 2017-08-02 10-40-14](https://user-images.githubusercontent.com/18212777/28865255-91cbc3fa-776f-11e7-94a0-4ba52a7a33f0.png)

[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/1185340/cuckoo.txt)
[analysis.txt](https://github.com/cuckoosandbox/cuckoo/files/1185341/analysis.txt)

**Comment by Nwinternights** [comment] 2017-07-29 23:26
https://github.com/cuckoosandbox/cuckoo/issues/1119

**Comment by jbremer** [comment] 2017-08-06 00:31
Yes, this is indeed a duplicate of #1119. We're still working on a fix. Closing as duplicate though ;)

**Closed by jbremer** 2017-08-06 00:31 UTC
