### ISSUE TITLE
Cuckoo Package: No items complete all the way through to reported.

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1361] opened 2017-03-25 02:48 UTC
It seem that reporting is hanging and never completing
this was run with  cuckoo -d process -r 1 to re-report task1 and thats where is stays for the last 30 mins
Seems to always hang on whats ever is after STRINGS.

--------------------------------------------------------------------

2017-03-25 15:46:43,834 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,834 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2017-03-25 15:46:43,835 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,835 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,835 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,836 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,836 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,836 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,836 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:43,837 [cuckoo.processing.snort] WARNING: Unable to run Snort as no pcap is available
2017-03-25 15:46:43,837 [cuckoo.core.plugins] DEBUG: Executed processing module "Snort" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:44,422 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"
2017-03-25 15:46:44,428 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/home/adroot/.cuckoo/storage/analyses/1"

------------------------------------------------------------------------------

**Comment by jbremer** [comment] 2017-03-25 09:21
Could you provide the full Cuckoo logs? Looks like you enabled Snort? Any other modules? Might be, e.g., our Snort support is outdated and won't automatically kill Snort after processing the PCAP etc.

**Comment by SparkyNZL** [comment] 2017-03-26 19:17
sure ill do a clean and send you some clean logs :)

**Comment by SparkyNZL** [comment] 2017-03-27 05:46
@jbremer Ok so finally sorted out the Yara issue, it seems to be something with Yara 3.5 i removed this and install 3.4 and it works fine ! so all samples are reporting now, but the screen shots are still missing :(

**Comment by doomedraven** [comment] 2017-03-27 06:05
i always have a lot of issues with yara 3.5.0, is why i use 3.4.0, and about screenshots the same here, missed

**Comment by jbremer** [comment] 2017-03-27 11:55
@SparkyNZL @doomedraven Do you have any reproducible scenario where `3.5.0` is obviously worse than `3.4.0`? I.e., a sample + rule that should work but doesn't on the latest etc?

**Comment by doomedraven** [comment] 2017-03-27 17:16
em i don't have them but i did another chance to 3.5 a bit ago and no way, it fails for me, i don't remember why right now, but by default i have hardcoded and comemnted in my deploy script don't use 3.5 xD

**Comment by SparkyNZL** [comment] 2017-03-27 20:31
yup, ill send you some stuff  and thinkgs so you can do your thing :)

**Comment by SparkyNZL** [comment] 2017-04-01 07:01
@jbremer  eeek i still havent done this, ill install it tomorrow and get you some samples.

**Comment by jbremer** [comment] 2017-04-21 01:21
@SparkyNZL Bump!

**Comment by jbremer** [comment] 2017-04-28 23:53
@SparkyNZL this issue won't stay open forever :)

**Comment by SparkyNZL** [comment] 2017-04-29 12:00
Oh bugger I forgot all about this I'll install 3.5 tomorrow and run some
samples up for u :)

**Comment by SparkyNZL** [comment] 2017-05-08 07:10
So i installed Yara 3.5 and sure enough i hangs on dropped files, Ill reinstall it during the week and restart the lab and flick u some samples, but 3.4 of yara  is much more stable

**Comment by SparkyNZL** [comment] 2017-05-21 06:58
OK I still have to do this, sorry about the delay getting back to you, ive been trying to sort some mogodb issues. :(

**Comment by jbremer** [comment] 2017-06-23 10:29
Closing as well :) let me know if you have samples etc.

**Closed by jbremer** 2017-06-23 10:29 UTC
