### ISSUE TITLE
rooter.py, CentOS

### ISSUE THREAD

**Issue by m-messiah** [cuckoosandbox/cuckoo#769] opened 2016-02-16 14:51 UTC
Hello! 
I see, rooter behavior is not documented anywhere, but it also used in Cuckoo-master, so, can anybody explain what it wants?

For example, I have cuckoo instance, running from root with VirtualBox routed through host-only if vboxnet0. Now, when analysis complete it removes vboxnet0, which prevents other analysis in future.

When I enable rooter in cuckoo.conf and enable vpn in vpn.conf rooter fails with message `OpenVPN binary is not available, please configure!` (openvpn installed on host, but of-course is not configured, because unneeded)

Which is the most beautiful way to bring it to work?

P.S. Now only this hack
```bash
vboxmanage hostonlyif ipconfig vboxnet0 --ip 10.31.37.1 --netmask 255.255.255.0".split())
```
can reassign ip to interface by cron every 2 minutes.
It is so awful!

**Comment by jbremer** [comment] 2016-02-16 14:55
It's used for routing Cuckoo analyses through one or more VPNs. If it works on CentOS, I'm not sure..
Your `vboxnet0` going down might be related to VirtualBox 5, if you're running that version.
We haven't come up with a solution for that yet.

**Comment by m-messiah** [comment] 2016-02-16 15:31
Do you mean VB5 is not tested for Cuckoo?

I know, that new behavior appears from this update: https://github.com/m-messiah/cuckoo/commit/7143f8c2fbd0241eb02084d76cebe272757f4fcc , but can't determine, which update broke this. I have using VB5 for a long time, and all was right.

**Comment by jbremer** [comment] 2016-02-16 16:05
Hmm, odd. Well, in that merge, if you look for `virtualbox.py`, there's actually nothing changed.. so I'm not sure then what the issue is.

**Comment by jekil** [comment] 2016-02-16 23:18
You can get the help for the command with the following:

```
$ python utils/rooter.py -h
usage: rooter.py [-h] [-g GROUP] [--ifconfig IFCONFIG] [--openvpn OPENVPN]
                 [--iptables IPTABLES] [--ip IP] [-v]
                 [socket]

positional arguments:
  socket                Unix socket path

optional arguments:
  -h, --help            show this help message and exit
  -g GROUP, --group GROUP
                        Unix socket group
  --ifconfig IFCONFIG   Path to ifconfig
  --openvpn OPENVPN     Path to openvpn
  --iptables IPTABLES   Path to iptables
  --ip IP               Path to ip
  -v, --verbose         Enable verbose logging
```

The default value for **--openvpn** is **/etc/init.d/openvpn** but this doesn't exists on RH/CentOS.
As today, the scripts supports only debian/ubuntu systems, i am going to put some love on it.

**Comment by m-messiah** [comment] 2016-02-17 09:25
1. Rooter - yes, maybe change openvpn bin to /usr/sbin/openvpn or some same would help. I can't start it without any openvpn configs.


2. Hostonlyif problem seems to appears by VirtualBox and Network-Manager, cut from /var/log/messages:
```syslog
Feb 17 10:17:37 cuckoo cuckoo.py: 2016-02-17 10:17:37,838 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label Windows7 to path /home/cuckoo/cuckoo/storage/analyses/1221/memory.dmp
Feb 17 10:17:44 cuckoo kernel: device vboxnet0 left promiscuous mode
Feb 17 10:17:44 cuckoo NetworkManager[942]: <info>  (vboxnet0): link disconnected (deferring action for 4 seconds)
Feb 17 10:17:44 cuckoo kernel: vboxnetflt: 4074 out of 4146 packets were not sent (directed to host)
Feb 17 10:17:46 cuckoo cuckoo.py: 2016-02-17 10:17:46,317 [volatility.debug] WARNING: #033[33mNoneObject as string: Cannot find process session#033[0m
Feb 17 10:17:46 cuckoo cuckoo.py: 2016-02-17 10:17:46,320 [volatility.debug] WARNING: #033[33mNoneObject as string: Cannot find process session#033[0m
Feb 17 10:17:46 cuckoo cuckoo.py: 2016-02-17 10:17:46,417 [volatility.debug] WARNING: #033[33mNoneObject as string: Pointer ObjectTable invalid#033[0m
Feb 17 10:17:48 cuckoo NetworkManager[942]: <info>  (vboxnet0): link disconnected (calling deferred action)
Feb 17 10:17:48 cuckoo NetworkManager[942]: <info>  (vboxnet0): device state change: activated -> unavailable (reason 'carrier-changed') [100 20 40]
```

vboxnet0 marked as ignored in NM. Not Cuckoo, but do you have any suggestions?

**Comment by jekil** [comment] 2016-02-17 12:25
@m-messiah changing it to /usr/sbin/openvpn is useless, because /usr/sbin/openvpn doesn't accept the same arguments passed to init script.
After commit bdc2128 we are using service instead of init.d script and it should be more portable.

**Comment by jbremer** [comment] 2016-04-28 20:04
I'm sorry, but I don't think we're going to officially support CentOS anytime soon - for all functionality anyway. So going to close this issue as unresolved, sorry.

**Closed by jbremer** 2016-04-28 20:04 UTC
Labels: Bug (confirmed)
