### ISSUE TITLE
RPC2 not found in agent.py - [ Cuckoo 2.0.5 ]

### ISSUE THREAD

**Issue by p3tr0v** [cuckoosandbox/cuckoo#2050] opened 2018-01-08 14:05 UTC
After installed cuckoo version 2.0.5 in ubuntu 16.04, i installed the agent in physical manchine (Windows 7 64bits).
When a submit a malware, cuckoo says in log:
`2018-01-08 11:51:43,740 [cuckoo.machinery.physical] DEBUG: Received unknown exception: <ProtocolError for 192.168.100.21:8000/RPC2: 404 Not Found>.
2018-01-08 11:51:43,745 [cuckoo.common.abstracts] DEBUG: Waiting 30 cuckooseconds for machine physical1 to switch to status ('running',)`

Reading the agent.py source code , i didn't find `@app.route("/RPC2", methods=["POST"])` 

Thats a bug?

--
Sorry, english is not my native language

**Comment by doomedraven** [comment] 2018-01-08 15:49
which agent version?

**Comment by p3tr0v** [comment] 2018-01-08 16:13
@doomedraven 
The agent version is "0.8"

Agente version is the default, I just used "pip -U" to install cuckoo.
Cuckoo's version is 2.0.5

**Comment by doomedraven** [comment] 2018-01-08 16:37
do search in issues by `RPC2` and you will see a lot of issues like this

**Comment by p3tr0v** [comment] 2018-01-08 17:07
@doomedraven 
With this exactly problem (RPC2 not found) , only one:
https://github.com/cuckoosandbox/cuckoo/issues/1396 , where @jbremer marked as "bug (confirmed)"
@jbremer  say to agent 0.8 in this issue https://github.com/cuckoosandbox/cuckoo/issues/1893
Thats version i'm using.

**Comment by smalinskiy** [comment] 2018-01-23 19:29
same for esxi machinery

**Comment by jbremer** [comment] 2018-02-04 09:26
Sorry, currently you can't use the New Agent for Physical analyses. You'll have to install the Old Agent - do you know where to find that?

**Comment by jbremer** [comment] 2018-02-04 09:48
Indeed, duplicate of #1396. Closing as duplicate.

**Closed by jbremer** 2018-02-04 09:48 UTC
