### ISSUE TITLE
Unable to submit large file using web interface, getting error "Something went wrong."

### ISSUE THREAD

**Issue by bipindubey** [cuckoosandbox/cuckoo#2295] opened 2018-05-31 12:19 UTC
I have installed and configured cuckoo 2.0.5 on my Ubuntu 14.04 (Host machine) with two Windows XP and Windows 7 as guest machine. I am able to analyse small files (size less than 1 MB) but not large file.

I am getting error "Something went wrong." on web interface after few second of ....Loading your submitted file.....

**Comment by doomedraven** [comment] 2018-05-31 12:28
without weblog impossible to help

**Comment by RicoVZ** [comment] 2018-05-31 14:15
Hi @bipindubey,

Thanks for posting an issue.

Could you please post logs/output generated by Cuckoo web while you are getting this error?
This will help us find the issue and help you solve it.

**Comment by cssxn** [comment] 2018-06-01 01:37
I've got the same issue yesterday. and I fixed that, It was a Character problem. so  to solve issue I changed my Sample filename to English.

**Comment by bipindubey** [comment] 2018-06-01 07:10
The web log after submitting a file (file size 5.1 MB) using web interface

[01/Jun/2018 12:01:03] "GET / HTTP/1.1" 200 27529
[01/Jun/2018 12:01:04] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/css/vendor.css HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/vendor.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/css/main.css HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/images/loading.gif HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/images/close.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/images/prev.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "GET /static/images/next.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:04] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 689
[01/Jun/2018 12:01:04] "GET /cuckoo/api/status HTTP/1.1" 200 1214
[01/Jun/2018 12:01:04] "GET /static/fonts/Roboto_italic_400_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:13] "POST /submit/api/presubmit/ HTTP/1.1" 302 0
[01/Jun/2018 12:01:13] "GET /submit/pre/65/ HTTP/1.1" 200 20145
[01/Jun/2018 12:01:15] "GET /submit/pre/65/ HTTP/1.1" 200 20145
[01/Jun/2018 12:01:15] "GET /static/css/vendor.css HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/css/main.css HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/vendor.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/images/prev.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/images/next.png HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/images/loading.gif HTTP/1.1" 304 0
[01/Jun/2018 12:01:15] "GET /static/images/close.png HTTP/1.1" 304 0

![cuckoo_error](https://user-images.githubusercontent.com/39795756/40826610-cdf8b2ee-6598-11e8-986b-3c7ea52cea52.png)

**Comment by RicoVZ** [comment] 2018-06-01 09:46
Thanks for posting the log. Can you post the name of the file you were submitting? I am wondering if it might contain characters which causes this error.

If it is possible, could you share the file? It would be useful for trying to reproduce this error.

**Comment by marcelmalware** [comment] 2018-06-04 12:47
@RicoVZ, here is a hash of a sample file which crashes on mine too. 
C82CFEAD292EECA601D3CF82C8C5340CB579D1C6

You can look it up on virustotal.

**Comment by bipindubey** [comment] 2018-06-05 05:39
I don't know what was happening, but it is working now. Thanks for support.

**Comment by bipindubey** [comment] 2018-06-05 07:16
hi guys, submission of large files works perfect when web server of cuckoo is run on localhost. however, the problem occurs when i run cuckoo web server on some IP and access it from some other machine in the network. It displays the message "Something went wrong". Below are the web access logs:

[05/Jun/2018 12:08:04] "GET /submit/ HTTP/1.1" 200 19891
[05/Jun/2018 12:08:04] "GET /static/css/vendor.css HTTP/1.1" 304 0
[05/Jun/2018 12:08:04] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 12:08:04] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:04] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 12:08:05] "GET /static/images/loading.gif HTTP/1.1" 304 0

**Comment by RicoVZ** [comment] 2018-06-05 11:04
Thanks for the update @bipindubey. Could you post a little more info on how you start cuckoo web?

What is the parameter for `-H` for which this error does happen? Is it a public IP?

Also, would it be possible to try the submit again and post a full HTTP log? :smile: 
You can accomplish this by starting cuckoo web and redirecting all output to a txt file: `cuckoo web -H someip -p someport &> output.txt`. After this, you can drag/drop the file into a Github comment.

I am trying to see if there is any HTTP error code in the log. So far, I see none.

**Comment by bipindubey** [comment] 2018-06-05 11:57
I am running cuckoo web server on a private IP of a network.
Output of **cuckoo web -H someip -p someport &> output.txt**

[05/Jun/2018 16:16:28] "GET / HTTP/1.1" 200 27529
[05/Jun/2018 16:16:29] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/css/vendor.css HTTP/1.1" 200 152014
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 200 8158
[05/Jun/2018 16:16:29] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/images/loading.gif HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 16:16:29] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 718
[05/Jun/2018 16:16:30] "GET /cuckoo/api/status HTTP/1.1" 200 1215
[05/Jun/2018 16:16:31] "GET /static/fonts/Roboto_italic_400_default.woff HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET / HTTP/1.1" 200 27529
[05/Jun/2018 16:17:16] "GET /static/css/vendor.css HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/images/loading.gif HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:16] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 718
[05/Jun/2018 16:17:17] "GET /cuckoo/api/status HTTP/1.1" 200 1216
[05/Jun/2018 16:17:32] "POST /submit/api/presubmit/ HTTP/1.1" 302 0
[05/Jun/2018 16:17:32] "GET /submit/pre/82/ HTTP/1.1" 200 20145
[05/Jun/2018 16:17:34] "GET /submit/pre/82/ HTTP/1.1" 200 20145
[05/Jun/2018 16:17:34] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/css/vendor.css HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 16:17:34] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/images/loading.gif HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 16:17:35] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /dashboard/ HTTP/1.1" 200 27517
[05/Jun/2018 16:20:56] "GET /static/css/vendor.css HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:56] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/images/loading.gif HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 16:20:57] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 718
[05/Jun/2018 16:20:59] "GET /cuckoo/api/status HTTP/1.1" 200 1215
[05/Jun/2018 16:21:01] "GET /analysis/ HTTP/1.1" 200 18840
[05/Jun/2018 16:21:01] "GET /static/css/vendor.css HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/css/main.css HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/vendor.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:01] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/images/loading.gif HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/images/next.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/images/close.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/images/prev.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[05/Jun/2018 16:21:02] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 27243

**Comment by doomedraven** [comment] 2018-06-05 11:58
you missed -d

**Comment by RicoVZ** [comment] 2018-06-05 12:31
Awesome @bipindubey.

I do not see all logs I expect, though. 
Did you try to submit the file that triggers the error while recording the log? :smile:
 If not, could you do that? Otherwise, some HTTP requests are missing in the log.

The goal is to record an exception that is likely being thrown.

**Comment by bipindubey** [comment] 2018-06-07 08:59
guys, i again tried to submit a file of size 3.8MB and captured the output in output.txt as mentioned by @RicoVZ cuckoo web -H someip -p 8000 &> output.txt. Attaching the file output.txt
[output.txt](https://github.com/cuckoosandbox/cuckoo/files/2079684/output.txt). do you want logs from tcpdump??

**Comment by RicoVZ** [comment] 2018-06-07 14:02
@bipindubey

Mhm, odd stuff, I still see not errors in the logs. Thanks for posting the things we need! :smile:  It is appreciated.

Could you also post the file that is triggered the error? (With original file name) Or the hash for this file?
I want to try and reproduce the error myself.

**Comment by bipindubey** [comment] 2018-06-08 04:46
@RicoVZ 
I am able to submit and analyze the large files when running the cuckoo web server on localhost, but the same is not possible when running web server on some private IP in the network. I am also attaching the file 
[worldreport.pdf](https://github.com/cuckoosandbox/cuckoo/files/2082949/worldreport.pdf)
It is not the issue particularly with this file. It is happening with any file larger than 1MB.
Your help is really appreciated.
 Thanks

**Comment by RicoVZ** [comment] 2018-06-08 09:42
Thanks for posting the file @bipindubey.
It seems the cause are the files. I also get the error when submitting this file. :smile:  (I can submit other large files)

Now.. On to finding the cause. We will keep you updated.

**Comment by bipindubey** [comment] 2018-06-08 11:55
@RicoVZ 
thanks for the reply, i am facing this problem with all the files larger than 1MB. Can you please share any file which is running successfully at your cuckoo web server with some IP and not on localhost.
thanks

**Comment by twesterhever** [comment] 2018-06-12 14:33
This issue can be reproduced here (mostly with compressed files containing several directory layers).

**Comment by RicoVZ** [comment] 2018-06-12 16:06
Hey @twesterhever, if they happens, could you share some samples/hashes? :smile: This should not happen. 

@bipindubey 
We have fixed two bugs that caused some errors or timeouts. Please upgrade your Cuckoo using `pip install -U cuckoo`, and this issue should be fixed. :smile: 

Feedback/confirmation would be appreciated.

**Comment by bipindubey** [comment] 2018-06-14 06:20
Thanks for fixing the issue. Now I am able to analyze the file that I have shared with you, but some other files are giving error like this one.
[ds80admin.pdf](https://github.com/cuckoosandbox/cuckoo/files/2101023/ds80admin.pdf)

**Comment by RicoVZ** [comment] 2018-06-14 08:44
@bipindubey Thanks for confirming! Onto the next issue :smile: 
I will try to verify it as soon as possible. Thanks for sharing the file.

**Comment by RicoVZ** [comment] 2018-06-14 09:15
@bipindubey What kind of error are you getting when submitting? I tried submitting this through the 2.0.6.1 web interface, but I do not run into any problems.

**Comment by jbremer** [comment] 2018-10-09 14:30
Closing issue for lack of additional information - please reopen if you have an update for us.

**Closed by jbremer** 2018-10-09 14:30 UTC
