### ISSUE TITLE
Cuckoo Package 2.0.4a5 , WGIU URL submit

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1738] opened 2017-07-29 05:02 UTC
When ever i submit a URL in the WGIU i get a BSON error saying  the file is to large (see below) 

This causes the analysis not to be entered into mongodb, which results in a 404 error when you try and view the report in the WGIU.

Regardless of the site, it seems to always think that the bson file is the same size

---------------------------------------------------------------------------------------------

https://google.com

2017-07-29 16:03:15,214 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 599, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
DocumentTooLarge: BSON document too large (25215786 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2017-07-29 16:03:15,300 [cuckoo.apps.apps] INFO: Task #1: reports generation completed

--------------------------------------------------------------------------------------------------

http://stuff.co.nz

2017-07-29 16:52:37,147 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 599, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
DocumentTooLarge: BSON document too large (200164874 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.

------------------------------------------------------------------------------------------------------

in the cwd/storage/analyes/1/logs the bson files are as follows

------------------------------------------------------------------------------------------------------

drwxrwxr-x  2 adroot adroot   4096 Jul 29 16:00 ./
drwxrwxr-x 10 adroot adroot   4096 Jul 29 15:56 ../
-rw-rw-r--  1 adroot adroot 232405 Jul 29 15:54 1528.bson
-rw-rw-r--  1 adroot adroot  11153 Jul 29 15:54 480.bson

-------------------------------------------------------------------------------------------------------

in the cwd/storage/analyes/1/logs the bson files are as follows

-------------------------------------------------------------------------------------------------------

drwxrwxr-x  2 adroot adroot    4096 Jul 29 16:09 ./
drwxrwxr-x 10 adroot adroot    4096 Jul 29 16:52 ../
-rw-rw-r--  1 adroot adroot 3690422 Jul 29 16:12 2176.bson
-rw-rw-r--  1 adroot adroot  230288 Jul 29 16:12 3020.bson
-rw-rw-r--  1 adroot adroot   15080 Jul 29 16:12 480.bson

--------------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment] 2017-07-29 05:29
This issue was introduced between 2.0.4a2 and 2.0.4a3

**Comment by jbremer** [comment] 2017-08-06 00:27
This has been an issue since forever :) we still have to give it a proper look.

**Comment by SparkyNZL** [comment] 2017-08-13 20:27
The BSON error has been an issue agreed. but for some reason cuckoo isn't reading the size correctly since 2.0.4a3, now they all fail regardless of the size of BSON files,  in 2.0.4a3 it would only fail if the BSON files were actually to large, now in 2.0.5a5 they report as being to large but actually aren't.

Cheers

**Comment by razuz** [comment] 2017-08-20 16:45
@SparkyNZL you're dumping all API calls with yara ? :)

**Comment by SparkyNZL** [comment] 2017-09-03 23:42
Ok so the reason this is now occuring is that cuckoo is now collecting all of the internet cache and temp files and this is blowing out the final BSON . so its now detecting every file writen to the following locations.

----------------------------------------------------------


C:\Users\cuckoo\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData
C:\Users\cuckoo\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content
C:\Users\cuckoo\AppData\Roaming\Microsoft\Windows\Cookies\
C:\Users\cuckoo\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\

----------------------------------------------------------

Also the memory dumps too are causing a "blow out in the BSON" file

Hope this is of some help.

To answer your question though Razuz, , i did have the API search turned on in reporting.

**Comment by razuz** [comment] 2017-09-04 10:56
tried to reproduce that ... for whatever reason I cannot ... only thing that blows up my BSON in bunch of ways is matching API calls with yara - but that's kind of known fact

**Comment by SparkyNZL** [comment] 2017-09-05 21:29
Hmm in this case it was just standard web site, so there should be no  Yara API in formation in it. can i send you the report DIR and get you to see if you can process it ?

**Comment by SparkyNZL** [comment] 2017-09-06 00:10
if you do a url to https://stuff.co.nz and live for 300s the /files is fill with stuff from these cache directories  directories.

**Comment by jbremer** [comment] 2017-12-04 20:04
Closing issue as duplicate of a known issue that has been reported in the past. Yes, we'll address this in the upcoming months. Thanks!

**Closed by jbremer** 2017-12-04 20:04 UTC
