### ISSUE TITLE
Unable to submit samples via web interface behind proxy

### ISSUE THREAD

**Issue by CSIRTUK** [cuckoosandbox/cuckoo#1397] opened 2017-04-12 08:49 UTC
Using the new release of Version 2.0, when I submit files via the web interface, locally or across my local network using the IP address, and a simple apache redirect to port 8000, everything works as it should.  However, when I try and access it from an external network using a similar redirect on our main web portal it shows the file upload but does not proceed to the pre-submit page.

On the web gateway the apache config uses the following lines to do the redirection, and I am using similar lines on the host to pass the requests received on port 80 on to port 8000.

ProxyPreserveHost on
ProxyPass / http://10.80.X.X/
ProcyPassReverse / http://10.80.X.X/

**Comment by MarkusTeufelberger** [comment] 2017-04-12 11:10
Maybe related to https://github.com/cuckoosandbox/cuckoo/issues/1391 especially if your proxy adds TLS.

Look for 301 redirects in the browser console for hints.

**Comment by jbremer** [comment] 2017-04-12 11:21
Yes, this certainly sounds like a duplicate of #1391. I'll give it a look ASAP.

**Comment by CSIRTUK** [comment] 2017-04-12 11:28
Thanks jbremer, just so you know I installed the alpha release this morning and that hasn't resolved the issue for me.

**Comment by MarkusTeufelberger** [comment] 2017-04-12 12:03
Then you need to add

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

to your local_settings.py

**Comment by jbremer** [comment] 2017-04-12 12:06
Would a relative redirect fix this issue? I'm looking for solutions, but AFAIK it's not all that weird to do a redirect to the created (submit in this case) ID after a POST request is made to submit a set of files / urls / whatever.

**Comment by MarkusTeufelberger** [comment] 2017-04-12 12:08
As far as I understood it, since HSTS was set on my proxy but django didn't know about https, it forwarded to an http link which silently caused a warning in the browser log and got blocked as insecure content is not allowed.

**Comment by CSIRTUK** [comment] 2017-04-13 09:01
This appears to be the same issue for me.  Enabling logging in chrome lets me see the following: [12238:12238:0413/095218.958838:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://cuckoo.xxxx.co.uk/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cuckoo.xxxx.co.uk/submit/pre/5/'. This request has been blocked; the content must be served over HTTPS.", source: https://cuckoo.xxxx.co.uk/ (0)

**Comment by CSIRTUK** [comment] 2017-04-13 09:34
Performing the same actions in Firefox results in a redirect to a blank page.

**Comment by jbremer** [comment] 2017-04-13 09:45
Hm yes, I'm open to suggestions as to how we can improve this. Preferably keeping my last comment here in mind.. :-)

**Comment by CSIRTUK** [comment] 2017-04-13 11:39
A relative redirect should fix it I would have thought.  The other relative
links are all working fine.

**Comment by jbremer** [comment] 2017-04-20 13:54
As per @seanthegeek in #1429 one should be able to fix this by putting it behind `uwsgi` as per our documentation (I believe these two issues are related). Could you please give that a try @CSIRTUK @MarkusTeufelberger?

**Comment by MarkusTeufelberger** [comment] 2017-04-20 14:10
I fixed it as mentioned by setting SECURE_PROXY_SSL_HEADER.

**Comment by jbremer** [comment] 2017-04-20 14:11
Good point, thanks @MarkusTeufelberger. I'll add that fix as a comment to `local_settings.py`.

**Comment by jbremer** [comment] 2017-04-20 14:47
Having provided 2 workarounds I think it's fine to close this issue. Thanks for the feedback!

**Closed by jbremer** 2017-04-20 14:47 UTC

**Comment by CSIRTUK** [comment] 2017-04-21 09:56
SECURE_PROXY_SSL_HEADER fix and that didn't work for me.  Going to try the uwsgi one instead.

**Comment by seanthegeek** [comment] 2017-04-21 10:17
@CSIRTUK There two parts to that header fix. In addition to adding that Django setting  You also need to add these lines to the NGINX configuration location / block:

```nginx
proxy_redirect off;
proxy_set_header X-Forwarded-Proto $scheme;
```

@jbremer I reccomend including these lines unvommented these settings uncommented in the generated NGINX configs. They will not harm non-https deployments, but mearly ensure the proper URL scheme is passed to Django. Likewise, the Django setting

```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```

Can be safely included by default, as it is only telling Django to use HTTPS when the reverse proxy supplies a request header of `HTTP_X_FORWARDED_PROTO`, with a value of `https`. plain HTTP is not affected.

Doing the above, combined with [uWSGI deployment]https://cuckoo.sh/docs/usage/web.html#web-deployment() described in the documentation will work for both HTTP and HTTPS sites.

Reference: https://djangodeployment.com/2017/01/24/fix-djangos-https-redirects-nginx/

**Comment by CSIRTUK** [comment] 2017-04-21 10:38
Thanks guys, had to make some additional changes so that my nginx was also
serving https rather than http and then change the apache config on the
gateway so that it would accept a self signed certificate but now it's all
working just fine.  Thanks for all the help :)

**Comment by jbremer** [comment] 2017-04-21 12:47
Oh sweet, thanks for that @seanthegeek! I'll take your word for it and apply those suggestions.

**Comment by jbremer** [comment] 2017-04-21 13:00
@seanthegeek See also the following commit 741c4c2422c2da3be435161a706f4f76642e00ae :)
