### ISSUE TITLE
Conducting dynamic analysis on ELF malware using cuckoo

### ISSUE THREAD

**Issue by Mohannadcse** [cuckoosandbox/cuckoo#1455] opened 2017-04-21 21:10 UTC
I'm trying to perform dynamic analysis on ELF malware, the dataset that I have comprises ELF files developed to run of different CPU architectures. I've deployed cuckoo host machine, and also created Ubuntu 16 guest machine using VirtualBox, the static part works, but facing difficulties with generating reports based on the dynamic analysis part, so the problem that I'm facing as follows:
1- Still couldn't find a sufficient description about the steps and requirements for conducting malware analysis using cuckoo, even in the official cuckoo documentation website, so has anyone tried to perform that? 
2- If I want to run the ELF on the other architectures like MIPS/ARM, what should I do in this case? can I use VirtualBox?

**Comment by doomedraven** [comment] 2017-04-21 22:02
i have builded cuckoo linux https://linux.huntingmalware.com/
and have arches: x32, x64, ppc, sparc, arm, mips, mipsel,

see in documentation ->  instalation -> linux
you have the basic info, and how to create vms you should do it by youself, and see my PRs for correct linux working as they now merged yet

**Comment by doomedraven** [comment] 2017-04-21 22:06
here you have everything what you need to start
https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/guest/linux.rst

**Comment by Mohannadcse** [comment] 2017-04-21 22:14
Thanks a lot for your comments. 
I've tried the 1st link, and received following error 
![error](https://cloud.githubusercontent.com/assets/15859139/25297811/de43ee48-26b5-11e7-9076-878461543271.jpg)

**Comment by doomedraven** [comment] 2017-04-21 22:16
i told you which arches i support, and i don't support motorola(your sample), neither sh4, i still need imrpove silent rejection of not supported arches

but as you can see no vm was selected for that task so is why you see that error

**Comment by doomedraven** [comment] 2017-04-21 22:17
see this as example 
https://linux.huntingmalware.com/analysis/1732/network/

**Comment by Mohannadcse** [comment] 2017-04-21 22:31
Appreciated, sorry for this confusion.
Please any advice for interpretation the behavioral report https://linux.huntingmalware.com/analysis/1746/behavior/ 
Why there is no network traffic generated ??

**Comment by doomedraven** [comment] 2017-04-21 22:32
bcz behavior part still very poor, but you can get network from https://linux.huntingmalware.com/analysis/1746/network/

**Comment by doomedraven** [comment] 2017-04-21 22:33
and i have added silent rejection of not supported arches, had it in past but all that updates sometimes forgetting some parts

**Comment by doomedraven** [comment] 2017-04-21 22:37
we have api up and running for bulk files upload/report retrieving

**Comment by Mohannadcse** [comment] 2017-04-21 22:41
Sounds great. Thanks a lot for the swift responses. But you still haven't addressed my concern regarding  interpretation the generated behavioral report https://linux.huntingmalware.com/analysis/1746/behavior/

**Comment by Mohannadcse** [comment] 2017-04-21 23:08
I went over the 2nd link, but still I don't understand what is the application that will be used for running the guest machine?? is it virtualbox or qemu, seems qemu, but how I can install qemu? and what should be the OS that will be configured on the guest machine?
Please need your advice and suggestion to resolve this problem. Since the link doesn't discuss this issue

**Comment by doomedraven** [comment] 2017-04-22 05:24
did you read the documentation which i pointed? https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/guest/linux.rst

it says qemu, and you have steps there how to install it
about gusts os, is which you want, but you will have problems get many of the arches, as many of the current linux distros doesn't support many arches, so that is up to you, you can use old debian for that

**Comment by doomedraven** [comment] 2017-04-22 05:25
and what do you mean about `Please any advice for interpretation the behavior report `? as I told that still poor, it uses systemtap or strace but it works on x32 only, on another arches it didn't work

**Comment by Mohannadcse** [comment] 2017-04-23 03:29
I meant by `interpretation the behavior report` is how to understand the output of the behavioral analysis, because the output is ambiguous  https://linux.huntingmalware.com/analysis/1746/behavior/ 
Thanks for the provided information

**Comment by Mohannadcse** [comment] 2017-04-23 03:35
I'm facing difficulties in configuring the guest machine, seems to me this link https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/guest/linux.rst 
makes some assumptions about configurations of the guest machine. 
Like what are these `machines = debian_x32, debian_x64, debian_arm, debian_mips, debian_mipsel` and received this error `Error: argument "br0" is wrong: Device does not exist` after issuing this command work with me `$ sudo ip link set tap_debian_x32 master br0`

**Comment by doomedraven** [comment] 2017-04-23 07:22
Because you need to configure qemu network, to be able use br0 interface, about behavior check man of strace how to understand it, im working on extension of behavior for all arches

**Comment by Mohannadcse** [comment] 2017-04-25 05:17
I received following error after configuring Debian_32 guest VM, and submitting the malware file. Any advice please 
![image](https://cloud.githubusercontent.com/assets/15859139/25369860/7d408a9a-294c-11e7-86dc-9209ae6e123c.png)

**Comment by Mohannadcse** [comment] 2017-04-25 05:21
Also, for the memory analysis, what should be the profile that needs to be configured ??
The following log on the terminal for the submitted error 

```
2017-04-25 00:11:14,495 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "f830f2e4d3b39fadaa509913f34a0ed7" (task #19, options "route=none,procmemdump=yes")
2017-04-25 00:11:14,504 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/think/Downloads/cuckoo/storage/binaries/1d8275d76ef0137ebb9ec9b96a3185104d24aa2b1bd7effae89463129166a98e"
2017-04-25 00:11:14,620 [lib.cuckoo.core.scheduler] INFO: Task #19: acquired machine Deb_32 (label=Deb_32)
2017-04-25 00:11:14,627 [modules.auxiliary.mitm] INFO: Started mitm interception with PID 32240 (ip=192.168.56.1, port=50001).
2017-04-25 00:11:14,632 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 32241 (interface=vboxnet0, host=192.168.56.101, pcap=/home/think/Downloads/cuckoo/storage/analyses/19/dump.pcap)
2017-04-25 00:11:18,802 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=Deb_32, ip=192.168.56.101)
2017-04-25 00:14:19,322 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Deb_32: the guest initialization hit the critical timeout, analysis aborted.
2017-04-25 00:14:19,481 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.
2017-04-25 00:14:20,173 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label Deb_32 to path /home/think/Downloads/cuckoo/storage/analyses/19/memory.dmp
2017-04-25 00:14:21,851 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/think/Downloads/cuckoo/storage/analyses/19/logs'.
2017-04-25 00:14:43,230 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/think/Downloads/cuckoo/modules/processing/memory.py", line 1028, in run
    results = VolatilityManager(self.memory_path).run()
  File "/home/think/Downloads/cuckoo/modules/processing/memory.py", line 948, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/home/think/Downloads/cuckoo/modules/processing/memory.py", line 59, in __init__
    self.init_config()
  File "/home/think/Downloads/cuckoo/modules/processing/memory.py", line 113, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

2017-04-25 00:14:43,231 [modules.processing.screenshots] ERROR: Could not find tesseract binary, screenshot OCR aborted.
25/4/2017 -- 00:14:43 - <Notice> - This is Suricata version 3.2RC1 RELEASE
25/4/2017 -- 00:14:45 - <Warning> - [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "/etc/suricata//threshold.config": No such file or directory
25/4/2017 -- 00:14:45 - <Notice> - all 9 packet processing threads, 4 management threads initialized, engine started.
25/4/2017 -- 00:14:45 - <Notice> - Signal Received.  Stopping engine.
25/4/2017 -- 00:14:45 - <Notice> - Pcap-file module read 86 packets, 10670 bytes
2017-04-25 00:14:45,455 [modules.processing.suricata] WARNING: Unable to find the files-json.log log file
2017-04-25 00:14:45,972 [lib.cuckoo.core.scheduler] INFO: Task #19: reports generation completed (path=/home/think/Downloads/cuckoo/storage/analyses/19)
2017-04-25 00:14:46,122 [lib.cuckoo.core.scheduler] INFO: Task #19: analysis procedure completed
```

**Comment by Mohannadcse** [comment] 2017-04-25 16:47
@jbremer Thanks, but why am I still receiving `moloch` error? do I need to modify anything?

**Comment by Mohannadcse** [comment] 2017-04-25 17:24
Also, still I'm receiving errors for running the `mitmdump`, still I'm receiving this error `mitmdump: No such file: "data/mitm.py" `, and where is the certificate should be stored? it was mentioned how to to do that for Windows guest (`analyzer/windows/bin/cert.p12`), but how about Linux guest??

**Comment by jbremer** [comment] 2017-04-25 18:16
Which version of Cuckoo are you using?

**Comment by Mohannadcse** [comment] 2017-04-25 18:17
Cuckoo Sandbox 2.0-rc2
and few minutes ago ran this command `sudo ./community.py -waf`

**Comment by Mohannadcse** [comment] 2017-04-25 18:51
Even your online setup doesn't show `moloch` results, following is my trial https://linux.huntingmalware.com/analysis/moloch/198.12.97.76//////

**Comment by doomedraven** [comment] 2017-04-25 18:58
@Mohannadcse bcz i don't have activated moloch xD

**Comment by jbremer** [comment] 2017-04-25 19:23
@Mohannadcse That functionality doesn't work for non-Windows at the moment. We have yet to implement transparent SSL interception - right now the `mitmproxy` integration requires setting a proxy in the VM. To be fair, at the time of its implementation, we didn't have the capability of implementing transparent inteception as the Cuckoo Rooter didn't exist yet (which will be required for that, naturally).

**Comment by jbremer** [comment] 2017-04-25 22:23
We've put out a new release, version `2.0.2`, which you may obtain through `pip install -U cuckoo`, including various improvements for the `Volatility` / `memory.py` issue posted above. Please check it out!

**Comment by Mohannadcse** [comment] 2017-04-25 22:26
Appreciated, but do I need to change the `.conf` files in the `conf directory` after the update?

**Comment by jbremer** [comment] 2017-04-25 22:29
You can now specify the VM profile by adding, e.g., `osprofile = WinXPSP2x86` to each VM. That's the only change.

**Comment by Mohannadcse** [comment] 2017-04-25 22:30
But I'm using Debian_X32 VM, not windows

**Comment by Mohannadcse** [comment] 2017-04-25 22:32
Received following log after running the pip command Exception:
SORRY for bothering 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/dist-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/appdirs-1.4.0.dist-info/METADATA'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by doomedraven** [comment] 2017-04-25 22:32
use vol.py's `imageinfo` plugin to get a correct profile, but it maybe will be needed to be created by yourself

**Comment by doomedraven** [comment] 2017-04-25 22:34
from the log you can see what is not cuckoo related, it would be very useful for all the devs if users start do a bit more of googling before post not related stuff

https://github.com/ActiveState/appdirs/issues/89

**Comment by jbremer** [comment] 2017-04-25 22:39
None of the Volatility integration in Cuckoo focuses on Linux VMs, so you're better off just disabling it in your case.

Regarding your stacktrace, make sure to have `pip` and `setuptools` up-to-date and if it fails a first time, just try it a second time! See also our documentation https://cuckoo.sh/docs/installation/host/installation.html#install-cuckoo

**Comment by Mohannadcse** [comment] 2017-04-25 22:39
@doomedraven I'm not very familiar with what you've described, can you please elaborate more. Thanks in advance
@doomedraven I'm doing a lot of Googling, the documentations isn't clear. How can I know this is not related stuff, I don't want to waste your time, but I spent lots of time trying to figure out these issues. And I highly appreciate your cooperation

**Comment by doomedraven** [comment] 2017-04-25 22:44
as @jbremer told, the linux vol support here is better to be disabled, as you would need to create your profiles per distribution/kernel etc, but that is already vol part not cuckoo. and you would need to extend the default memory.py as it also not include linux vol plugins, etc

if in path there no cuckoo, that is not cuckoo related ;)
as `IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/appdirs-1.4.0.dist-info/METADATA'` <- no cuckoo word in the path  
and with the first result in google you can see the same issue in related branch

the documentation got big upgrade and improvement thanks to @jbremer , just read if first, but everything to understand how it works, and it will be more clearly

**Comment by Mohannadcse** [comment] 2017-04-25 22:52
@doomedraven Thanks for the explanation. As stated for the beginning, I'm analyzing ELF malware files, Windosw malware isn't my target, and according to https://cuckoosandbox.org/ Cuckoo supports analysis under Linux. 
Also, I noticed the version on the github is different than the available version from the previous link. 

I'm saying that, as am pretty sure you keen to improve Cuckoo. Anyway, if it can't analyse ELF, wondering if you have tried Limon http://malware-unplugged.blogspot.com/2015/11/setting-up-limon-sandbox-for-analyzing.html

**Comment by doomedraven** [comment] 2017-04-25 22:57
@Mohannadcse it supports also android and mac os x, but that is part of dark magic :D 
how it can't analyze elf? it can yo saw it in my setup :P
i saw Monnapa's, but the purposes is different, and cuckoo focus is more on windows, but it getting improved a lot linux analyzer as im working on it, but it still hard beta

maybe for your need limon will be better, that is your decision

**Comment by Mohannadcse** [comment] 2017-04-25 23:02
Your setup is doing the static analysis, where I'm interested in capturing behavioral aspects, which rely on the dynamic analysis. The reason I'm focusing on ELF is that I'm conducting research about IoT Malware. The problem of Limon, it not support other arch like ARM and MIPS. Anyways, thanks for you both @doomedraven @jbremer

**Comment by jbremer** [comment] 2017-04-25 23:06
Fwiw, a few days ago you linked https://linux.huntingmalware.com/analysis/1746/behavior/ which is most certainly behavioral information / dynamic analysis ;-) Please do let us know if you make progress on your research though - would be happy to see additional improvements!

**Comment by doomedraven** [comment] 2017-04-25 23:06
you sample has behavior(https://linux.huntingmalware.com/analysis/1818/summary), it has network capture, so it totally different, it still not have the static part. I added the rest of the arches not only x32 arch support behavior part now, but that part is still private as i'm working on it, yup that is limon problem, but you always can fork it and port to qemu :P

**Comment by Mohannadcse** [comment] 2017-04-26 15:11
Much appreciated. Can you please elaborate more on the scoring system, and how it's measured. 
![image](https://cloud.githubusercontent.com/assets/15859139/25441720/a5c2c7d6-2a68-11e7-8404-3045dd4eb122.png)

**Comment by doomedraven** [comment] 2017-04-26 15:20
it based on this https://github.com/cuckoosandbox/community

in linux it still not developed, as there no linux signatures

**Comment by omid-s** [comment] 2017-06-13 14:04
I have been trying to follow 
https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/guest/linux.rst
the problem is the kernel module would not build. I have been searching a good deal to get it compiled no luck so far ... I have tried it on ubuntu 12,14,16. has any body have a step by step instruction to be done on fresh install ?

**Comment by daanfs** [comment] 2017-06-13 14:07
@omid-s have you installed the kernel debug symbols?

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C8CAB6595FDFF622

codename=$(lsb_release -c | awk  '{print $2}')
sudo tee /etc/apt/sources.list.d/ddebs.list << EOF
deb http://ddebs.ubuntu.com/ ${codename}      main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-security main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-updates  main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-proposed main restricted universe multiverse
EOF

sudo apt-get update
sudo apt-get install linux-image-$(uname -r)-dbgsym
```

What is the exact error you're getting?

**Comment by omid-s** [comment] 2017-06-13 14:32
thanks for the quick response :) 
`semantic error: while resolving probe point: identifier 'kprobe' at /usr/share/systemtap/tapset/linux/nd_syscalls.stp:1416:32
        source: probe nd_syscall.fork.return = kprobe.function("do_fork").return
                                               ^

semantic error: while resolving probe point: identifier 'kprobe' at /usr/share/systemtap/tapset/linux/x86_64/nd_syscalls.stp:178:40
        source: probe nd_syscall.vm86_warning.return = kprobe.function("sys32_vm86_warning").return
                                                       ^

Pass 2: analyzed script: 790 probe(s), 284 function(s), 29 embed(s), 34 global(s) using 510840virt/46252res/7020shr/40068data kb, in 5190usr/1180sys/9931real ms.
Pass 2: analysis failed.  [man error::pass2]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.`

I just did what you said and re tried the :
sudo stap ...... 
I also tried --poison-cache to make sure (to my limited knowledge ) I'm getting a reload. 
the above is the error I'm getting. and this is ubuntu trusty 14.04

**Comment by daanfs** [comment] 2017-06-13 14:40
@omid-s Do you have the linux-headers package as well?

The following should work and has been tested on a fresh ubuntu 17.04 install:

```
sudo apt-get install systemtap
sudo apt-get install gcc
sudo apt-get install linux-headers-$(uname -r)

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C8CAB6595FDFF622

codename=$(lsb_release -c | awk  '{print $2}')
sudo tee /etc/apt/sources.list.d/ddebs.list << EOF
deb http://ddebs.ubuntu.com/ ${codename}      main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-security main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-updates  main restricted universe multiverse
deb http://ddebs.ubuntu.com/ ${codename}-proposed main restricted universe multiverse
EOF

sudo apt-get update
sudo apt-get install linux-image-$(uname -r)-dbgsym

wget https://raw.githubusercontent.com/cuckoosandbox/cuckoo/master/stuff/strace.stp
sudo stap -p4 -r $(uname -r) strace.stp -m stap_ -v

sudo mkdir /root/.cuckoo
sudo mv stap_.ko /root/.cuckoo/
sudo ufw disable
```

**Comment by doomedraven** [comment] 2017-06-13 14:52
@omid-s 
>> getting. and this is ubuntu trusty 14.04

in one of the issues I already told, i had the same problems on old kernels, so try it on >=16.04

**Comment by vikaskarunakaran** [comment] 2018-01-31 06:00
@doomedraven 

Do we need to create 2 adapters host-only and NAT like Windows guests or just follow the bellow steps ?

$ sudo tunctl -b -u cuckoo -t tap_debian_x64
$ sudo ip link set tap_debian_x64 master br0
$ sudo ip link set dev tap_debian_x64 up
$ sudo ip link set dev br0 up

**Comment by doomedraven** [comment] 2018-01-31 07:17
one per vm is fine

**Comment by vikaskarunakaran** [comment] 2018-01-31 07:40
@doomedraven 

The commands network commands has to be run on host OS right ?

Also what is the interface br0 ? I can see virbr0 and eth0 on my host. eth0 is on dhcp

Do I need to configure static IP on guest as like in windows  ?

**Comment by doomedraven** [comment] 2018-01-31 07:52
yes on host, virbr is for kvm, br is for qemu, that depends of your hypervisor, in kvm you will can only to use x32/x64 linux vms. yes set static ips

**Comment by vikaskarunakaran** [comment] 2018-01-31 08:41
@doomedraven 
Can you explain me how this tapping works.
Because, in windows guest one host-only adapter with static IP will be used for Host to Guest communication and vice versa. Another NAT Adapter will be used for internet connectivity inside the guest.
So how does this concept work with linux guest using qemu ?

Also I cannot see br0 in my host interfaces.

**Comment by doomedraven** [comment] 2018-01-31 11:08
tapX is like vnetX in kvm, if you can't find it mean you didn't install it correctly or something like that `search for qemu-ifup`, you have a lot of mans in internet how to do that correctly

https://en.wikibooks.org/wiki/QEMU/Networking#TAP

**Comment by jbremer** [comment] 2018-02-04 09:11
Does that resolve all your questions, @vikaskarunakaran ?

**Comment by vikaskarunakaran** [comment] 2018-02-04 10:32
Sorry for not responding.

yes it solved, 

thanks @doomedraven

**Closed** 2018-02-04 10:32 UTC
Labels: Issue close upcoming

**Comment by doomedraven** [comment] 2018-02-04 20:53
you are welcome :)

**Comment by thevidocq** [comment] 2018-11-15 18:43
@doomedraven Can I have access to your Cuckoo istance with the API? We want to analyze malspam samples with cortex and thehive applications. Thanks.

**Comment by doomedraven** [comment] 2018-11-15 18:44
for https://linux.huntingmalware.com/ i can give but that is linux only, and windows is private

**Comment by thevidocq** [comment] 2018-11-15 18:52
@doomedraven Well! For Windows, If you give to me the access, We can share malware samples/analysis. Our analysis/day is low. What do you think about this? My email is luca.dassisti@gmail.com. Thanks.

**Comment by doomedraven** [comment] 2018-11-15 18:53
as for me i would be happy to do that ,but i can't do that as my cuckoo are nto exposed to internet and has a lot of not shared data, sorry

**Comment by thevidocq** [comment] 2018-11-15 19:01
@doomedraven I understand, I would be very grateful if you send to me the information about API for linux. Many thanks.

**Comment by lantuin** [comment] 2019-07-31 13:24
Hello!! I'm trying to analyze elf files. I've create da Ubuntu 17.04 VM x64 machine following instructions on https://cuckoo.sh/docs/installation/guest/linux.html#preparing-x32-x64-ubuntu-18-04-linux-guests and I'm able to compile correctly stap_.ko. When I submit an elf file I don't have any behavioral analysis and in log I receive following error:

2019-07-31 15:08:56,224 [cuckoo.core.resultserver] ERROR: Netlog client requested banned path: 'logs/all.stap'

Do you have any idea?

Thanks!
