### ISSUE TITLE
Analysis failed: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Leurak** [cuckoosandbox/cuckoo#982] opened 2016-06-29 11:38 UTC
This error seems to happen quite often for me, causing the analysis to fail. Also, `CRITICAL: BsonParser lacking data` is written into the console every few seconds (if that has something to do with the issue).

I found nothing about this bug so I reported it here.

**Comment by botherder** [comment] 2016-06-30 07:46
Can you provide samples that produce this?

**Comment by Leurak** [comment] 2016-07-04 11:19
I don't know what sample I checked at this time. But when I restarted, the same executable made no errors. So I think this is not sample-related, but seems to be some rare bug that stays until Cucko is restarted (or misconfiguration).

**Comment by mcm** [comment] 2016-07-06 03:53
I encountered this issue using the sample from http://malware-traffic-analysis.net/2016/07/05/index.html -- specifically, 2016-07-05-Magnitude-EK-payload-Cerber.exe. Eventually, though, analysis finished and a report was generated.

Snippet of the log:

```
2016-07-05 23:42:39,944 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=analysis-win7-1, ip=192.168.1.100)
2016-07-05 23:44:59,283 [lib.cuckoo.core.resultserver] WARNING: Uploaded file length larger than upload_max_size, stopping upload.
2016-07-05 23:45:04,129 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: dictionary changed size during iteration
2016-07-05 23:45:59,171 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Suricata" for task #39:
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/modules/processing/suricata.py", line 289, in run
    self.parse_eve_json()
  File "/opt/cuckoo/modules/processing/suricata.py", line 147, in parse_eve_json
    "src_port": event["src_port"],
KeyError: 'src_port'
2016-07-05 23:47:01,923 [lib.cuckoo.core.scheduler] INFO: Task #39: reports generation completed (path=/opt/cuckoo/storage/analyses/39)
2016-07-05 23:47:01,987 [lib.cuckoo.core.scheduler] INFO: Task #39: analysis procedure completed
```

I will try resubmitting to see if that fixes it.

**Comment by KillerInstinct** [comment] 2016-07-06 11:43
Suricata is iffy at populating a bunch of fields. Sometimes it missies fields, you'll need to throw it in a try/except or define the dict keys/value pairs beforehand.

**Comment by jbremer** [comment] 2016-07-06 14:03
@mcm With this latest commit (see above) that issue should be resolved - thanks!

**Comment by KillerInstinct** [comment] 2016-07-06 14:07
I think this may causes issues with the web interface, where you'll try to iterate a value that does not exist, if the a value doesn't exist with .get() -- I think it should be .get(value, "None") so that it gets initialized to None if there is no value.

**Comment by jbremer** [comment] 2016-07-06 14:10
Just checked the Suricata Web Interface template, I think it'll be mostly fine, but thanks for the heads up.

**Comment by mcm** [comment] 2016-07-06 14:14
@KillerInstinct @jbremer I tested using .get(value, "n/a") but I got a template rendering error trying to do reverse url (sorry don't have the error in front of me) for moloch, when src_port was "n/a". Using .get(value, "0") worked for me instead though.

For reference, it was failing when the protocol was ICMP, which wouldn't have a src_port/dest_port.

**Comment by jbremer** [comment] 2016-07-06 14:33
Interestingly the `dictionary changed size during iteration` is coming from the Guest, it's just that the logging was incomplete on the Cuckoo side.
@Leurak @mcm Could you please share the version of Cuckoo you're running, any changes that you performed on the Cuckoo Analyzer, and perhaps the analysis options?

**Comment by mcm** [comment] 2016-07-06 16:01
I'm running from a git checkout:

```
commit fa069dde006f9490cf543775e6ca7b881bce4432
Author: Jurriaan Bremer <jbr@cuckoo.sh>
Date:   Wed Jun 22 17:22:50 2016 +0200

    include analysis information in the export/import logic
```

I haven't made any changes to the Analyzer as far as I know, and the analysis options are default I think.... I have suricata enabled but that's the only change I think. I'm able to test anything you need as well, this isn't quite a production system for us (yet).

**Comment by doomedraven** [comment] 2016-07-06 16:03
i think first you need update your cuckoo to latest commit, as it almost 15 days old already

**Comment by jbremer** [comment] 2016-07-06 16:04
That's fine, I don't think much changed that would alter this behavior. Time to add some more debugging information perhaps..

**Comment by mcm** [comment] 2016-07-06 16:04
I can definitely update it and try again. I'll report back results.

**Comment by jbremer** [comment] 2016-07-06 16:29
@mcm

**Comment by doomedraven** [comment] 2016-07-06 16:31
heh is interesting, on first execution i got the same bson error, but once i reexecuted, not reprocessed report, i didn't get it

**Comment by doomedraven** [comment] 2016-07-06 16:38
well for me now everything works fine, suricata, and no more bson errors

**Comment by mcm** [comment] 2016-07-06 17:52
@jbremer Here you go:

```
2016-07-06 13:48:04,555 [lib.cuckoo.core.resultserver] WARNING: Uploaded file length larger than upload_max_size, stopping upload.
2016-07-06 13:48:10,742 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: dictionary changed size during iteration
Traceback (most recent call last):
  File "C:\xswmktusj\analyzer.py", line 778, in <module>
  File "C:\xswmktusj\analyzer.py", line 765, in run
  File "C:\xswmktusj\analyzer.py", line 504, in complete
  File "C:\xswmktusj\analyzer.py", line 122, in dump_files
RuntimeError: dictionary changed size during iteration
```

**Comment by KillerInstinct** [comment] 2016-07-06 17:58
Need to increase your upload limit in cuckoo.conf (i think thats where it is)

Whats happening is, instead of aborting the upload when we hit the "size too large" issue, it terminates the upload (thus truncating it). Since BSON is structured, truncating it breaks the structure and it detects that as a size change.

**Comment by mcm** [comment] 2016-07-06 17:59
Hmm I've already increased to 100mb, but I suppose its entirely possible that its much larger than that. Let me increase it some more and try again.

**Comment by KillerInstinct** [comment] 2016-07-06 18:00
Ransomware BSON's can be enormous depending on how long you run the analysis for. Honestly I don't see a reason for not having the size be <= 1GB, python processes it all just fine. It may just take an extra minute or so really (current generation server processors)

**Comment by mcm** [comment] 2016-07-06 18:01
I bumped it to 1GB, we'll see what happens. Rerunning now.

**Comment by jbremer** [comment] 2016-07-06 18:06
True story, what do you think about bumping the default to 128mb rather than the current 10mb @KillerInstinct?

**Comment by mcm** [comment] 2016-07-06 19:44
After bumping this to 1GB, the error seems to have vanished. I'm going to bump it back down to 100Mb to confirm, as someone mentioned earlier that it seemed to come-and-go.

**Comment by mcm** [comment] 2016-07-06 20:04
Actually I spoke too soon. Clicking "reboot analysis" wasn't enough to trigger this, I got hardly any analysis from that (but did get an error saying that I needed to update the agent). I resubmitted the file with a 1gb max upload, and I no longer got the upload warning but got this:

```
2016-07-06 15:44:46,605 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "2016-07-05-Magnitude-EK-payload-Cerber.exe" (task #44, options "route=none,procmemdump=yes")
2016-07-06 15:44:46,646 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/8564b5286ae6282be441dacad9de9215f4498fca94def27b30c1291f1326cf32"
2016-07-06 15:44:46,698 [lib.cuckoo.core.scheduler] INFO: Task #44: acquired machine analysis-win7-1 (label=4f85cf65-2863-4181-5a0e-a5750a44ae51)
2016-07-06 15:44:46,735 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 17326 (interface=eth1, host=192.168.1.100, pcap=/opt/cuckoo/storage/analyses/44/dump.pcap)
2016-07-06 15:45:51,341 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=analysis-win7-1, ip=192.168.1.100)
2016-07-06 15:48:25,932 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: dictionary changed size during iteration
Traceback (most recent call last):
  File "C:\rqpafuusvu\analyzer.py", line 778, in <module>
  File "C:\rqpafuusvu\analyzer.py", line 765, in run
  File "C:\rqpafuusvu\analyzer.py", line 504, in complete
  File "C:\rqpafuusvu\analyzer.py", line 122, in dump_files
RuntimeError: dictionary changed size during iteration

2016-07-06 15:50:44,840 [lib.cuckoo.core.scheduler] INFO: Task #44: reports generation completed (path=/opt/cuckoo/storage/analyses/44)
2016-07-06 15:50:44,926 [lib.cuckoo.core.scheduler] INFO: Task #44: analysis procedure completed
```

Based on the fact that this is a Cerber sample, I wonder if there's still some file encryption happening in when the agent is trying to dump the files? I'm not familiar with the agent and how it operates though so I'm just speculating (or randomly guessing, one of those).

**Comment by jbremer** [comment] 2016-07-06 20:06
That's what I was thinking - new `dropped files` coming in while the Analyzer is trying to upload all the currently registered dropped files.

**Comment by jbremer** [comment] 2016-07-06 20:11
@mcm Could you apply the following patch and try again? Thanks!

```
diff --git a/analyzer/windows/analyzer.py b/analyzer/windows/analyzer.py
index c6a44ec..7572b91 100644
--- a/analyzer/windows/analyzer.py
+++ b/analyzer/windows/analyzer.py
@@ -119,8 +119,8 @@ class Files(object):
 
     def dump_files(self):
         """Dump all pending files."""
-        for filepath in self.files:
-            self.dump_file(filepath)
+        while self.files:
+            self.dump_file(self.files.keys()[0])
 
 class ProcessList(object):
     def __init__(self):
```

**Comment by mcm** [comment] 2016-07-06 20:19
So that solved that problem. I got the following but I suspect the timeout is normal for a Ransomware sample:

```
2016-07-06 16:12:34,038 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "2016-07-05-Magnitude-EK-payload-Cerber.exe" (task #45, options "route=none,procmemdump=yes")
2016-07-06 16:12:34,080 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/8564b5286ae6282be441dacad9de9215f4498fca94def27b30c1291f1326cf32"
2016-07-06 16:12:34,114 [lib.cuckoo.core.scheduler] INFO: Task #45: acquired machine analysis-win7-1 (label=4f85cf65-2863-4181-5a0e-a5750a44ae51)
2016-07-06 16:12:34,167 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 18824 (interface=eth1, host=192.168.1.100, pcap=/opt/cuckoo/storage/analyses/45/dump.pcap)
2016-07-06 16:13:36,801 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=analysis-win7-1, ip=192.168.1.100)
2016-07-06 16:16:37,640 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2016-07-06 16:17:44,437 [lib.cuckoo.core.scheduler] INFO: Task #45: reports generation completed (path=/opt/cuckoo/storage/analyses/45)
2016-07-06 16:17:44,562 [lib.cuckoo.core.scheduler] INFO: Task #45: analysis procedure completed
```

This is probably a separate issue, but I noticed that the web interface is incorrectly rendering the error from the guest though:

Error: Error from the Cuckoo Guest: %s

But otherwise, that seems to have taken care of it.

**Comment by doomedraven** [comment] 2016-08-05 08:15
i just did git pull, to updateto latest version, and getting the same error 

```
2016-08-05 10:10:20,612 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: dictionary changed size during iteration
Traceback (most recent call last):
  File "C:\ypksm\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\ypksm\analyzer.py", line 765, in run
    self.complete()
  File "C:\ypksm\analyzer.py", line 504, in complete
    self.files.dump_files()
  File "C:\ypksm\analyzer.py", line 122, in dump_files
    for filepath in self.files:
RuntimeError: dictionary changed size during iteration
```


but it's not permanent, i pushed 2 analysis of ipinfo.io for some tests, and one of the analysis got this error

**Comment by jbremer** [comment] 2016-08-05 10:57
@doomedraven can you try the patch I proposed above? Thanks!

**Comment by doomedraven** [comment] 2016-08-05 11:07
let me try, but the problem is what that error is not permanent, from 10 analysis of the same thing, i got it only it 3 times, let me push new queue of analysis with patch

**Comment by doomedraven** [comment] 2016-08-05 12:28
@jbremer with this patch no errors, i did 20 analysis

**Comment by jbremer** [comment] 2016-08-08 15:57
I've pushed the proposed patch that was supposed to work. Still wondering about the default dropped file filesize limit, but other than that going to close this issue.

**Closed by jbremer** 2016-08-08 15:57 UTC
Labels: Bug (to verify)
