### ISSUE TITLE
Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.generic" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by 007scorpio** [cuckoosandbox/cuckoo#1377] opened 2017-04-03 18:05 UTC

**Comment by doomedraven** [comment] 2017-04-03 18:24
No details no bug ;)

**Comment by 007scorpio** [comment] 2017-04-03 18:28
Traceback (most recent call last):
  File "C:\rdnpzfxje\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\rdnpzfxje\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.generic" start function raised an error: Unable to execute the initial process, analysis aborted.

**Comment by doomedraven** [comment] 2017-04-03 18:35
No cuckoo version, no hypervisor software version, no hash/url whcih trigger error, etc

**Comment by 007scorpio** [comment] 2017-04-03 18:40
cuckoo version = 2.0-rc2
virtualbox version = 5.1.18


Sorry... the error does not give much info except the few i wrote... thanks

**Comment by doomedraven** [comment] 2017-04-03 19:08
But ehat trigger that? Any url/hash?

**Comment by 007scorpio** [comment] 2017-04-04 09:04
i submitted a .exe malware file please.

**Comment by doomedraven** [comment] 2017-04-04 09:06
ok but we don't have access to your .exe xD so we can't reproduce
if you want a good support, provide good info to devs so they can reproduce it

**Comment by yeejay** [comment] 2017-04-04 16:52
Run cuckoo with -d flag and post the results.  Also post configs, etc.

Reporting an issue without details is useless.

**Comment by 007scorpio** [comment] 2017-04-04 19:34
fixed it... Thanks all :)

**Comment by jbremer** [comment] 2017-04-04 19:37
@007scorpio and what was the fix?

**Comment by jbremer** [comment] 2017-04-21 01:24
I guess I'll be closing this issue - if you do have some feedback, let us know.

**Closed by jbremer** 2017-04-21 01:24 UTC
