### ISSUE TITLE
 Cannot connect to libvirt

### ISSUE THREAD

**Issue by gqqcode** [cuckoosandbox/cuckoo#1190] opened 2016-11-28 06:36 UTC
1. cuckoo sanbox version：Cuckoo Sandbox 2.0-rc1
2. virtual machine ：kvm
```
2016-11-28 14:31:09,548 [lib.cuckoo.core.scheduler] ERROR: Cannot connect to libvirt
2016-11-28 14:31:09,591 [lib.cuckoo.core.scheduler] CRITICAL: A critical error has occurred trying to use the machine with name WinXp_X64-3 during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).
2016-11-28 14:31:09,592 [lib.cuckoo.core.scheduler] WARNING: Unable to stop machine WinXp_X64-3: Cannot connect to libvirt
2016-11-28 14:31:09,743 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/Cuckoo/cuckoo/storage/analyses/78628/logs'.

```

**Comment by gqqcode** [comment] 2016-11-28 06:48
How to solve it？

**Comment by allthemalwarz** [comment] 2016-11-29 19:22
Is the user running cuckoo a member of the 'libvirtd' group?  This error is normally because the user does not have permissions to interact with libvirt.

**Comment by gqqcode** [comment] 2016-11-30 01:41
@allthemalwarz Just started running is no problem，but  there was a problem in five days。
I use the super user to perform

**Comment by doomedraven** [comment] 2016-12-04 22:24
first of all try to update to cuckoo rc2, i think the problem is also with permissions related as you need to add user to kvm and libvirt groups

**Comment by doomedraven** [comment] 2016-12-04 22:27
```
usermod -G libvirtd -a cuckoo
usermod -G kvm -a cuckoo
```

or root in your case ,but better run it with not full privileged user

**Comment by gqqcode** [comment] 2016-12-07 03:58
@doomedraven Thank you for the answer, I can ask you a question? Distributed sandbox should be how to deploy it?
I do not understand the document did not understand what is the case of distributed sandbox.I used two cuckoo nodes, which sent samples to only one node when submitting the virus samples.Can you give me a detailed step? Thank you

**Comment by doomedraven** [comment] 2016-12-07 09:31
@gqqcode i don't use official dist.py or dist app
We have upgraded dist.py 

Docu how to setup
https://github.com/spender-sandbox/cuckoo-modified/blob/master/docs/book/src/usage/dist.rst

File, it should be 99% compatible, you have to change this, the rest should works just fine:
1. task_ids to task_id here https://github.com/spender-sandbox/cuckoo-modified/blob/master/utils/dist.py#L296

2. you should care about archives, see my cuckoomx pull request
https://github.com/spender-sandbox/cuckoo-modified/blob/master/utils/dist.py

**Comment by gqqcode** [comment] 2016-12-08 01:03
@doomedraven Thank you

**Comment by gqqcode** [comment] 2016-12-08 07:24
@doomedraven Why can not I submit a sample?
the errors
```
curl http://localhost:9003/tasks -F file=@/home/gqq/virus/1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by doomedraven** [comment] 2016-12-08 10:29
ah yah it disabled need to update documentation, you need to add tasks with normal api, as you would add them normally and it will automatically pick them for distributed

**Comment by doomedraven** [comment] 2016-12-08 10:41
also you need add this to reporing.conf and configure it properly

```
[distributed]
enabled = no
remove_task_on_slave = no
# distributed cuckoo database, to store nodes and tasks info
db = sqlite:///dist.db
# directory where to store samples until analysis is finished
# will move samples to storage/binaries once analysis is finished
samples_directory = /tmp/distributed_cuckoo_samples
# tried before declare node as dead and deactivate it
dead_count = 5
# number of threads witch will retrieve files as memdump, pcap in background
retriever_threads = 4
```

**Comment by jbremer** [comment] 2017-12-04 21:08
Closing issue as resolved. Feel free to reopen if required. Thanks!

**Closed by jbremer** 2017-12-04 21:08 UTC
