### ISSUE TITLE
MogoDB issue with YARA rules

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2914] opened 2019-12-03 13:56 UTC
Hi,
Cuckoo 2.0.7, Ubuntu 16.04
I have integrated yara rules available on Github, and I have a reporting problem after this integrarion when the size of the analysis report exceeds 16M, with the problem of MongoDB "Document too large".
thanks.

**Comment by Evert0x** [comment] 2019-12-03 16:59
This is a duplicate from https://github.com/cuckoosandbox/cuckoo/issues/358

**Comment by RicoVZ** [comment] 2019-12-09 10:35
Hi nadir3392,

Thanks for posting an issue.

It is indeed a duplicate of #358 (potential solutions are posted here). Unfortunately, it is not something that is easily solved without throwing away data.

**Closed** 2019-12-09 10:35 UTC
