### ISSUE TITLE
Web Console -404

### ISSUE THREAD

**Issue by avinashx11** [cuckoosandbox/cuckoo#2262] opened 2018-05-09 05:25 UTC
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:In web page i am getting 404 error.

Kindly help us in this issue to get resolved at the earliest, Thanks in Advance.

Thanks & Regards,
Avinash.V

**Comment by doomedraven** [comment] 2018-05-09 06:50
logs?

**Comment by avinashx11** [comment] 2018-05-09 06:50
[09/May/2018 02:43:56] "GET /cuckoo/api/status HTTP/1.1" 200 620
- Broken pipe from ('127.0.0.1', 60553)
 Error checking for the latest Cuckoo version:
HTTPSConnectionPool(host='cuckoosandbox.org', port=443): Max retries exceeded with url: /updates.json?version=2.0.5 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection
object at 0x7f09f0156090>: Failed to establish a new connection:
[Errno -2] Name or service not known',))!

**Comment by doomedraven** [comment] 2018-05-09 06:56
disable the check for updates in cuckoo.conf

**Comment by doomedraven** [comment] 2018-05-09 12:40
please search that error on issues, there many like that and other has responses so one of them can be useful for you

**Comment by avinashx11** [comment] 2018-05-10 04:51
Hi,

Thanks a lot for your response.
Your fix worked now i am not getting any error but while submitting the exe file in web console still 404 error is coming.
But URL is working fine. Are we missing any configuration related things.
Please help us in resolving this issue.

Thanks & Regards,
Avinash.V

**Comment by avinashx11** [comment] 2018-05-10 09:52
Hi Team,

We getting report while we submitting through command prompt. and the report is fine.
When we trying to submit via web console it routes to 404 error.
kindly help on this are we missing any configuration issue. 
I am using Firefox  ESR 24.5.0 in RHEL machine.
![error](https://user-images.githubusercontent.com/18083850/39863952-d35c2a66-5465-11e8-9288-c9b687c11430.PNG)

**Comment by doomedraven** [comment] 2018-05-10 10:53
logs? in which link exactly? more details plz

**Comment by avinashx11** [comment] 2018-05-10 12:43
Hi ,

We upgraded the firefox browser now its working fine.
But we cant able to find screenshots in the report.

**Comment by doomedraven** [comment] 2018-05-10 14:03
no logs no problem

**Comment by doomedraven** [comment] 2018-05-11 11:30
>> i try to run cuckoo community for getting screenshot 

you mean signatures? Bcz screenshots doesnt have nothing to see with community

What about ping www.github.com? It looks like your host has problems with internet connection not cuckoo problem

**Comment by avinashx11** [comment] 2018-05-11 13:09
Oh thanks a lot for your support i need to submit larger file size sample its showing error in gui but when i am trying in command prompt its seems working do we need update any change in web settings.

**Comment by doomedraven** [comment] 2018-05-11 14:17
dude you still didn't do anything from what i told, no logs, no ping, nothing of nothing, in that way impossible to help you

**Comment by avinashx11** [comment] 2018-05-14 09:28
Hi,

Very sorry for the late reply.
I am getting following error in command prompt
"POST /submit/api/filetree/ HTTP/1.1" 200 847
- Broken pipe from ('127.0.0.1', 48164)"

But when i am trying to submit the same file in command prompt i am able to get perfect analysis report.

**Comment by doomedraven** [comment] 2018-05-16 11:02
google "django broken pip from" maybe that will help you

**Comment by avinashx11** [comment] 2018-06-01 09:46
Hi,

Thanks a lot for your support now our instance is up and running.
But in the analysis report, we can see hash value is incorrect in the static analysis. Attaching the screenshots for your reference.

![img-20180531-wa0021](https://user-images.githubusercontent.com/18083850/40834527-b784cb04-65ae-11e8-95a4-fe3f0f6f59dd.jpg)
![img-20180531-wa0022](https://user-images.githubusercontent.com/18083850/40834528-b7c45d3c-65ae-11e8-9f0a-3c0c11a38a02.jpg)

**Comment by RicoVZ** [comment] 2018-06-01 10:14
Hi avinashx11,

Could you post the file for which you get incorrect hashes. :smile:  This way we can confirm. 
Are the screenshots from different Cuckoo setups? How much time was between the analysis?

I tried getting the file for the first screenshot, and the latest Cuckoo (2.0.5.3) does calculate the correct sha1 hash (according to their website: '9105df8945ef1b9977f9fc5a2eb4a6ac53abf638'.

**Comment by avinashx11** [comment] 2018-06-01 12:02
Hi Rico,

I tried for multiple samples the hashes were incorrect in new updated setup.
Yes, its the screenshots from different version of setup.
Analysis time is default for both.
Sha 1 is also seems incorrect .
Are we missed something in the setup.

**Comment by RicoVZ** [comment] 2018-06-01 13:48
Ok, I understand. Can you post the files you submitted? I cannot reproduce it otherwise.
You can upload the files by dragging them into the comment box.

**Comment by avinashx11** [comment] 2018-06-04 06:44
Hi Rico,
The file sample is more than 10MB, this error is applicable for all samples.
Kindly let us know are missed anything in updated version.

**Comment by avinashx11** [comment] 2018-06-04 06:47
Still if you want the sample file, Kindly download in the download link
https://git-scm.com/download/win

**Comment by avinashx11** [comment] 2018-06-05 01:48
Hi Rico,
Can you please help on this issue, Why the modifications in Hash file is happening.
Kindly help us in fixing this issue.

**Comment by RicoVZ** [comment] 2018-06-05 12:21
Of course @avinashx11 I cannot (yet) reproduce the error, however.

I see I can download the file, could you still upload your local version(s)? (You can drag/drop them into a comment if they are zipped).

I suspect the file is being changed somehow, as the hashes are correct when I create an analysis for the file I download from your specified location.

Also, can you please use the command `md5sum <path of submitted file>`, and post the output?

**Comment by avinashx11** [comment] 2018-06-06 07:14
Hi Rico,

Thanks a lot for your support.
I used the command md5sum <path of submitted file>  and i rebooted the machine and now its working fine.
Now i am facing two issue 

- when i am submitting large files through web GUI it was not submitting properly it displays "Something Went Wrong".

-I just tried installing Ubuntu guest machine and agent it responding to the base machine but when i am submitting the file sample the file itself not dropping inside guest machine. We need to change any configuration settings to change.

Kindly help on this issue to get it resolved.

**Comment by RicoVZ** [comment] 2018-06-06 12:29
Good to see it is working now. :smile: 

>when i am submitting large files through web GUI it was not submitting properly it displays "Something Went Wrong".

Could you share the sample or its hash with us so we can try to reproduce this error?
Also, could you post the full web server log when this error occurs? This way we can find the cause. :smile: 

>the file sample the file itself not dropping inside guest machine.

Can you clarify a little more what happens exactly? Are there any errors, for example?
What agent have you installed in the Ubuntu guest?

**Comment by avinashx11** [comment] 2018-06-14 13:18
Hi Rico,

We have attached the entire log file for the web GUI error and for the Ubuntu guest machine error.

Below is the hash of the sample file that we have submitted through web GUI.

MD5: 28d3932f714bf71d78e75d36aa2e0fb8

[log.txt](https://github.com/cuckoosandbox/cuckoo/files/2102456/log.txt)
[Ubuntulog.txt](https://github.com/cuckoosandbox/cuckoo/files/2102457/Ubuntulog.txt)0.

**Comment by RicoVZ** [comment] 2018-06-25 12:01
@avinashx11 Sorry for the late answer.

Yes, thank you. For now, the details are fine :smile: 
That file is 903MB. It is very likely a timeout is causing this error. We are currently working on increasing the timeouts.

For now, I would also advice to update to Cuckoo 2.0.6.2, using `pip install -U cuckoo`. It is a new release from a few days ago containing some patches.

**Comment by avinashx11** [comment] 2018-06-26 05:36
Hi Rico,

Thanks a lot for your response.
Reg: Ubuntu error
We running agent.sh in analysis machine. The agent it responding to the base machine but when i am submitting the file sample the file itself not dropping inside guest machine. We need to change any configuration settings to change.

**Comment by RicoVZ** [comment] 2018-06-26 18:09
@avinashx11 

What agent are you using? :smile: 

The agent to use is: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/agent/agent.py
This is the agent that Cuckoo communicates with.

This page should also help a bit:
https://cuckoo.sh/docs/installation/guest/linux.html

Can you share the `analysis.log` file with us? I suspect it fails to start.

**Comment by avinashx11** [comment] 2018-07-03 09:44
Hi Rico,

Very sorry for the late reply.
We using the same version of agent in client machines still the analyses is not happening.
Can you please help on this issue to resolve it.

Thanks once again for your support.

**Comment by RicoVZ** [comment] 2018-07-03 12:30
@avinashx11 Can you share your `analysis.log`

**Comment by jbremer** [comment] 2018-10-09 16:07
Closing for lack of additional information, feel free to reopen.

**Closed by jbremer** 2018-10-09 16:07 UTC
