### ISSUE TITLE
Failing to Submit Url from Distributed API

### ISSUE THREAD

**Issue by prats84** [cuckoosandbox/cuckoo#1185] opened 2016-11-25 04:18 UTC
Unable to Submit a Url using the Distributed Restful api - api/task (curl localhost:9003/api/task -F file=@<filename>). The api cuckoo/distributed/distributed/views/api.py only checks for Files names and nothing for URLs.

**Comment by jbremer** [comment] 2016-11-25 07:42
Feel free to submit a PR to handle this :-)

**Comment by jbremer** [comment] 2016-11-25 07:43
Please note that - where possible - some unit tests would be useful, as this changes (in a good way) some core principals of Distributed Cuckoo.

**Comment by jbremer** [comment] 2017-02-25 10:59
Closing as duplicate of #1232 (or the other way around, but that issue is a little bit more active).
Please, if you have the time to PR this functionality, do let me know ;-)

**Closed by jbremer** 2017-02-25 10:59 UTC

**Comment by prats84** [comment] 2017-03-29 22:26
I will be working on this feature from April 2nd week.
