### ISSUE TITLE
cuckoo dependencies error.

### ISSUE THREAD

**Issue by rajksbth** [cuckoosandbox/cuckoo#2462] opened 2018-09-03 09:12 UTC
While running cuckoo 2.0.6 its showing
`pkg_resources.DistributionNotFound: The 'scapy==2.3.2' distribution was not found and is required by Cuckoo`

OS: Ubuntu 16.04
I have installed it through pip.

> (cenv)cuckoo@ansible-node-cuckoo:~$ cuckoo -d
Traceback (most recent call last):
  File "/home/cuckoo/cenv/bin/cuckoo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cuckoo/cenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scapy==2.3.2' distribution was not found and is required by Cuckoo

>

**Comment by doomedraven** [comment] 2018-09-03 09:13
`sudo pip install scapy==2.3.2`

**Comment by rajksbth** [comment] 2018-09-03 09:18
Thanks @doomedraven but its already mentioned in setup.py to install dependencies so why i need to install it manually.

**Comment by doomedraven** [comment] 2018-09-03 09:19
to try fix manually the error xD, if you read error cuckoo can't find that, do search in pip if it available

**Comment by rajksbth** [comment] 2018-09-03 09:26
I have checked in setup.py its there in extra dependencies.

> extras_require={
        ":sys_platform == 'win32'": [
            "requests==2.13.0",
        ],
        ":sys_platform == 'darwin'": [
            "requests==2.13.0",
        ],
        ":sys_platform == 'linux2'": [
            "requests[security]==2.13.0",
            "scapy==2.3.2",
        ],
        "distributed": [
            "gevent==1.1.1",
            "psycopg2==2.6.2",
        ],
        "postgresql": [
            "psycopg2==2.6.2",
        ],
        "weasyprint": [
            "weasyprint==0.36",
        ],
    },

> 

>

**Comment by SubhasisMukh** [comment] 2018-09-14 05:53
This issue should be closed by now as the problem is solved. Right? @doomedraven

**Comment by doomedraven** [comment] 2018-09-14 07:39
Only owner and @jbremer has right to close

**Closed** 2018-09-21 05:50 UTC
