### ISSUE TITLE
no such device error

### ISSUE THREAD

**Issue by Killerwhale91** [cuckoosandbox/cuckoo#1436] opened 2017-04-19 18:15 UTC
2017-04-20 02:46:55,099 [cuckoo.core.scheduler] INFO: Using "kvm" as machine manager
2017-04-20 02:46:59,220 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-20 02:46:59,234 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-20 02:47:06,592 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "img-526162500.pdf" (task #5, options "procmemdump=yes,route=none")
2017-04-20 02:47:06,656 [cuckoo.core.scheduler] INFO: Task #5: acquired machine TestWinXP (label=TestWinXP)
2017-04-20 02:47:06,669 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 20514 (interface=eth0, host=192.168.100.100, pcap=/root/.cuckoo/storage/analyses/5/dump.pcap)
2017-04-20 02:47:12,804 [cuckoo.core.guest] INFO: Starting analysis on guest (id=TestWinXP, ip=192.168.100.100)
2017-04-20 02:50:39,160 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-04-20 02:50:39,191 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?

**Comment by doomedraven** [comment] 2017-04-19 18:34
Do search of apparmor in issues and tou will get many responses

**Comment by jbremer** [comment] 2017-04-20 10:29
I think `eth0` simply doesn't exist. Did you properly configure your setup?

**Comment by jbremer** [comment] 2017-04-20 23:19
Duplicate of #1437, closing issue.

**Closed by jbremer** 2017-04-20 23:19 UTC
