### ISSUE TITLE
I couldn't upload large files to cuckoo

### ISSUE THREAD

**Issue by DannyJohns** [cuckoosandbox/cuckoo#754] opened 2016-02-10 07:40 UTC
I'm using Cuckoo Sandbox on Ubuntu 14.04 and a Windows7-x86 as a Guest OS on virtualbox and everything is fine except for files larger than 60 MB.
I edited 'cuckoo.conf' file and set the upload_max_size and analysis_size_limit to 9048576000 (9 GB).
I always upload my files through submit.py API and get this error for large files:

**cuckoo1: unable to upload malware to analysis machine: Fault 1: "type'exceptions.MemoryError':" **

**Comment by jbremer** [comment] 2016-02-10 12:34
In the Old Agent we're using XMLRPC which is pretty limited. If you try the New Agent (https://github.com/jbremer/agent) you might have more luck. Do let us know ;-)
Also, how much memory does your VM have assigned?

**Comment by jbremer** [comment] 2016-03-03 00:14
Closing this issue as duplicate of #764 (mostly because that issue has a more exact title).
Please report your findings - if any - there.

**Closed by jbremer** 2016-03-03 00:14 UTC

**Comment by bipindubey** [comment] 2018-05-31 10:04
Hi,
I am using the latest version of cuckoo i.e 2.0.5 While using the web interface of cuckoo for submitting the files, i am unable to submit files larger than 1MB. However submit from command line is working fine. I have also replaced the old python agent with the new one. My host OS is ubuntu 14,04 and guest machines are winxp and win7.

**Comment by RicoVZ** [comment] 2018-05-31 10:15
Hi @bipindubey ,

What is the exact error you are getting when uploading a file larger than 1 MB in the web interface?

Just as a tip: it might be better to create a new issue for question, as a comment on an old issue is likely to go unnoticed by most people. :smile:
