### ISSUE TITLE
Critical Bug in Cuckoo

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2255] opened 2018-05-01 13:10 UTC
Hi,

I have found 1 interesting bug in the cuckoo, I have analyzed 1 setup on my cuckoo machine and on your web portal (mlwr.ee) also. But cuckoo was unable to install the setup on the guest machine. Cuckoo was unable to click on the **Install** button. I have cross checked the human.py file also. install name was not there, I thought may be human.py is case sensitive So I have added the "Install" name in the list also but still cuckoo is not able to install the binary on cuckoo machine. Following is the url of that sample you can check the image part also its stop that thing only. 

http://mlwr.ee/analysis/2104674/summary/

You can also download the sample from the above link.

Waiting for positive reply asap.
.
Thanks & Regards
Seantree

**Comment by RicoVZ** [comment] 2018-05-01 15:02
Hi seantree,

Thanks for reporting this issue. I cannot say what the issue is, but I will look into it. At this time we are working on a new version of the human module.

Thanks again for reporting it.

**Comment by seantree** [comment] 2018-05-02 05:07
One more thing is there if the setup has checkboxes than cuckoo is not able to click on the checkboxes.
The above setup has that feature also and cuckoo didn't click on that.

**Comment by RicoVZ** [comment] 2018-05-02 14:05
Ah yes, that is correct, it only clicks buttons. I put it on my planning to look into implementing the checking of check/radiobuttons.

**Comment by jbremer** [comment] 2018-10-09 14:33
Closing issue for now.

**Closed by jbremer** 2018-10-09 14:33 UTC
